/*----------------------------------------------------------------------------
|
|   Config file for Advance Search Fields.
|
|
|   written for opt/oss/pkg/frontend/OSfInternalUIServer
|   written by Deepu Krishnamurthy & Alok Upendra Kamat.
|
|   October 2013
|
\---------------------------------------------------------------------------*/

module.exports.IntAdvSrch = {
    "OrderOrigin": {
        "all": "All",
        "OriginatingSystem": {
            "ePrime": "ePrime",
            "ecl": "eClaims",
            "cca": "Contact Center CCA",
            "wat": "Watson",
            "mad": "MAD - COMPAQ",
            "eop": "EOP",
            "elf": "Elf",
            "iscs_aus": "ISCS AUS",
            "iscs_ca": "ISCS CA",
            "iscs_hk": "ISCS HK",
            "iscs_kr": "ISCS KR",
            "iscs_my": "ISCS MY",
            "iscs_sg": "ISCS SG",
            "iscs_ar": "ISCS AR",
            "iscs_mx": "ISCS MX",
            "iscs_br": "ISCS BR",
            "iscs_de": "ISCS DE",
            "iscs_fr": "ISCS FR",
            "iscs_gb": "ISCS GB",
            "iscs_es": "ISCS ES",
            "iscs_se": "ISCS SE",
            "iscs_ch": "ISCS CH",
            "ebay_de": "EBAY DE",
            "grs": "GRS"
        },
        "SubmissionMethod": {
            "iscs_hrepp": "HREPP",
            "iscs_auspub": "AUSPUB",
            "iscs_capub": "CAPUB",
            "iscs_hkpub": "HKPUB",
            "iscs_krpub": "KRPUB",
            "iscs_mypub": "MYPUB",
            "iscs_sgpub": "SGPUB",
            "iscs_arpub": "ARPUB",
            "iscs_mxpub": "MXPUB",
            "iscs_brpub": "BRPUB",
            "tdc": "TDC",
            "sm_Phone": "Phone",
            "sm_Fax": "Fax",
            "sm_Email": "Mail",
            "sm_Web": "Web",
            "doe": "DOE",
            "edi": "EDI",
            "kiosk": "Kiosk",
            "omui": "OMUI"
        },
        "OESystem": {
            "sapr00": "Fusion Americas",
            "sapfap": "Fusion APJ",
            "sapr01": "Fusion EMEA",
            "sapap": "RSAP AP",
            "sapd7c": "SAP D700",
            "sapcpo": "SAP SAIL EMEA",
            "sapclp": "SAP CALADO",
            "velocity": "Velocity",
            "sapvista": "VISTA",
            "omsAP": "OMS APJ",
            "omsEU": "OMS EMEA",
            "omsUS": "OMS NA/LA/CA",
            "sappn1": "NGOM AMS",
            "sappo1": "NGOM EMEA",
            "sappj1": "NGOM APJ",
            "sappw1": "NGOM SW"
        },
        "OFSystem": {
            "sc_sapr00": "Fusion Americas",
            "sc_sapfap": "Fusion APJ",
            "sc_sapr01": "Fusion EMEA",
            "sc_sapap": "RSAP AP",
            "sc_sapd7c": "SAP D700",
            "sc_sapcpo": "SAP SAIL EMEA",
            "sc_sapclp": "SAP CALADO",
            "sc_velocity": "Velocity"
        }
    },
    "SearchByStatuses": {
        "Sapuserstatus": "",
        "UserStatusCategory": {
            "OrderEntry": {
                "oe_cr": "Credit hold",
                "oe_cfg": "Configuration Hold",
                "oe_doc": "Missing document",
                "oe_info": "Missing information",
                "oe_pri": "Pricing",
                "oe_pro": "Product",
                "oe_stax": "Tax Hold, T&Cs",
                "oe_acc": "Account",
                "oe_bitf": "Bitfone Order",
                "oe_cont": "Contract",
                "oe_cust": "Customer",
                "oe_cins": "Customer Inspection",
                "oe_cmov": "Customer MOV (Min Order Value)",
                "oe_crp": "Customer Road Permit",
                "oe_data": "Data Setup Error",
                "oe_deal": "Deal",
                "oe_dpri": "Deal Pricing",
                "oe_dupo": "Duplicate PO",
                "oe_eord": "eOrder Auto Hold",
                "oe_fulcr": "Fulfillment Credit",
                "oe_leas": "Leasing Issue",
                "oe_lic": "License / RPL Issue",
                "oe_ois": "OIS Fallout",
                "oe_oee": "Order Entry Error",
                "oe_pay": "Payment / Cash in Advance",
                "oe_res": "Reservation Order",
                "oe_so": "Sales Office Hold",
                "oe_serv": "Services",
                "oe_ship": "Ship Hold",
                "oe_shto": "Ship To Issues",
                "oe_skel": "Skeleton Order",
                "oe_supp": "Supplier Info Issue",
                "oe_vdps": "VDPS Order",
                "oe_oth": "Other"
            },
            "FactoryFulfillment": {
                "ff_cfg": "Config hold",
                "ff_doc": "Unschedule",
                "ff_mat": "Material hold",
                "ff_chg": "Change",
                "ff_cons": "Consolidated Delivery Hold",
                "ff_alli": "Alliance Hold",
                "ff_alloc": "Allocation Issue",
                "ff_cred": "Credit Reload",
                "ff_esc1": "Escalate/Expedite Lev. 1",
                "ff_esc2": "Escalate/Expedite Lev. 2",
                "ff_esc3": "Escalate/Expedite Lev. 3",
                "ff_fact": "Factory Hold",
                "ff_exp": "Export Hold",
                "ff_npi": "NPI",
                "ff_obs": "Obsolete Product",
                "ff_plant": "Plant Issue",
                "ff_prod": "Product Hold",
                "ff_shipm": "Shipment Hold",
                "ff_tba": "TBA",
                "ff_oth": "Other"
            },
            "Shipping": {
                "ship_tra": "Traffic",
                "ship_mer": "Merge",
                "ship_sch": "Scheduled",
                "ship_fo": "Fallout",
                "ship_ship": "Other"
            },
            "Billing": {
                "bill_inv": "Invoice",
                "bill_part": "Partial Invoice",
                "bill": "Other"
            },
            "FallOut": {
                "fo_sap": "SAP",
                "fo_ois": "OIS"
            },
            "Status": {
                "st_awcf": "Awaiting Config Check",
                "st_awcr": "Awaiting Credit",
                "st_awrp": "Awaiting Release to Production",
                "st_ffw": "FF WIP",
                "st_oew": "OE WIP",
                "st_shw": "Ship WIP"
            },
            "Cancel": {}
        }
    },
    "SearchByDates": {
        "orderDate": "Purchase Order Date",
        "hprecieve": "HP Receive Date",
        "factshipDate": "Fact Ship Date",
        "custshipDate": "Cust Ship Date",
        "eadDate": "Earliest Arrival Date",
        "sddDate": "SDD",
        "podDate": "POD Date",
        "invoDate": "Invoice Date",
        "quoteDate": "Quote Creation Date",
        "webordDate": "WebOrder Creation Date",
        "changedSince": "Changed Orders"
    },
    "SearchTotalOrderAmount": {
        "TotalAmountInclTax": {
            "exact_with_comma_dot": "exact  1,234.00",
            "exact_with_dot_comma": "exact  1.234,00",
            "approx_with_comma": "approx 1,234.00",
            "approx_with_dot": "approx 1.234,00",
            "ls_eq_comma": "    <= 1,234.00",
            "ls_eq_dot": "    <= 1.234,00",
            "gr_eq_comma": "    >= 1,234.00",
            "gr_eq_got": "    >= 1.234,00"
        },
        "TotalAmountWOTax": {
            "exact_with_comma_dot": "exact  1,234.00",
            "exact_with_dot_comma": "exact  1.234,00",
            "approx_with_comma": "approx 1,234.00",
            "approx_with_dot": "approx 1.234,00",
            "ls_eq_comma": "    <= 1,234.00",
            "ls_eq_dot": "    <= 1.234,00",
            "gr_eq_comma": "    >= 1,234.00",
            "gr_eq_got": "    >= 1.234,00"
        },
        "TotalAmountInclTaxInUSDollars": {
            "exact_with_comma_dot": "exact  1,234.00",
            "exact_with_dot_comma": "exact  1.234,00",
            "approx_with_comma": "approx 1,234.00",
            "approx_with_dot": "approx 1.234,00",
            "ls_eq_comma": "    <= 1,234.00",
            "ls_eq_dot": "    <= 1.234,00",
            "gr_eq_comma": "    >= 1,234.00",
            "gr_eq_got": "    >= 1.234,00"
        },
        "TotalAmountWOTaxInUSDollars": {
            "exact_with_comma_dot": "exact  1,234.00",
            "exact_with_dot_comma": "exact  1.234,00",
            "approx_with_comma": "approx 1,234.00",
            "approx_with_dot": "approx 1.234,00",
            "ls_eq_comma": "    <= 1,234.00",
            "ls_eq_dot": "    <= 1.234,00",
            "gr_eq_comma": "    >= 1,234.00",
            "gr_eq_dot": "    >= 1.234,00"
        }
    },
    "PortalUserID": {
        "": "Please Select",
        "b2b": "B2B-Portal",
        "ppro_emea": "Smart-Portal-EMEA",
        "pweb": "Partner-Portal-NA",
        "ppro": "Partner-PRO-APJ",
        "gpp_lar": "GPP-LAR",
        "iscs": "ISCS",
        "psweb": "PublicSector-Web",
        "corp": "CorporateAccounts",
        "ext": "DirectAccess"
    },
    "Repository": {
        "all": "all orders",
        "open": "only live order",
        "qtcuid": "only QTC uid orders(OSV)",
        "closed": "only history order"
    },
    "GroupFilter": {
        "all": "All",
        "otd_noa": "no acknowledgement report",
        "otd_tba": "TBA report",
        "otd_akn": "not shp'd/passed ack date report",
        "otd_re_ack": "re ack orders report",
        "cust_sh_not_inv": "customer shipped not invoiced",
        "reg_on_ma_hold": "complete landed on manual hold",
        "reg_on_cr_hold": "complete landed on credit hold",
        "reg_on_hold": "complete landed on hold",
        "partial_landed": "partial landed",
        "open_backlog": "open backlog",
        "late_backlog": "late backlog",
        "await_pod": "awaiting POD",
        "delivered": "complete delivered orders",
        "clean_backlog": "backlog to be reviewed",
        "custship_not_bill": "cust shipped not billed",
        "block_invo": "blocked invoices",
        "block_orders": "blocked orders",
        "fix_delivery": "fix delivery orders"
    },
    "OrderType": {
        "all": "All",
        "trade": "Trade",
        "lease": "Lease",
        "debit": "Debit",
        "srq": "SRQ",
        "trade_lease": "Trade & Lease",
        "trade_lease_srq": "Trade & Lease & SRQ",
        "internal": "Internal",
        "demo": "Demo",
        "resale": "Resale",
        "return": "Return",
        "credit": "Credit",
        "statistical": "Statistical",
        "contract": "Contract Order",
        "sw_contract": "SW Contract",
        "sw_contract_renewal": "SW Contract Renewal",
        "sw_contract_migrations":"SW Contract Migrations",
        "carepack": "Care Pack",
        "no_charge": "No Charge Order"
    },
    "OrderStatus": {
        "all": "All",
        "submitted": "Submitted",
        "admin": "Admin",
        "processing": "Admin/Processing",
        "acked": "Admin/Acked",
        "prod": "Production",
        "prod_done": "ProductionDone",
        "fact_ship": "Shipped from Factory",
        "ech": "Registered",
        "cust_ship": "Shipped to Customer",
        "delv": "Delivered",
        "invo": "Invoiced",
        "open": "Open Orders",
        "closed": "Closed Orders",
        "cancelled": "Canceled",
        "notfship": "not Shipped from Factory",
        "notcship": "not Shipped to Customer",
        "notdelv": "not Delivered",
        "notinvo": "not Invoiced",
        "ShipInvoiceStatus": {
            "f_shipped": "Order fully Shipped",
            "p_shipped": "Order partial Shipped",
            "n_shipped": "Order not Shipped",
            "f_invoiced": "Order fully Invoiced",
            "p_invoiced": "Order partial Invoiced",
            "n_invoiced": "Order not Invoiced"
        },
        "HeaderStatus": {
            "c_admin": "Admin (header)",
            "c_prod": "Production (header)",
            "c_cons": "Consolidation (header)",
            "c_shipped": "Shipped (header)",
            "c_delved": "Delivered (header)"
        }
    },
    "SearchByNumbers": {
        "asset_tag": "Asset Tag No",
        "b2bid": "OIS ID No",
        "eop_id": "EOP ID",
        "cust_fam_no": "Cust Family No",
        "csn": "Cust Ship No",
        "cust_no": "Customer No",
        "eclaim_no": "eClaim No",
        "fsn": "Fact Ship No",
        "mac_addr": "Mac Address",
        "ncrf_no": "NCRF number",
        "purch_agree": "Purch Agreement",
        "hp_quote_no": "Quote No",
        "sal_number": "SAL No",
        "serial_no": "Serial No",
        "imei": "IMEI (Telco)",
        "web_order_no": "Web Order No",
        "gvt_contract_number": "Gvt Contract No",
        "wawf_number": "WAWF Number",
        "account_name": "Account Name",
        "leg_ord_type": "Legacy Order Type",
        "mci": "Master Contract ID",
        "opportunity_id": "Opportunity ID",
        "rebate_request_id": "Rebate Request ID"
    },
    "SearchByCodes": {
        "CDCode": "",
        "DealPriceID": "",
        "DCCode": "",
        "EID": "",
        "IdCode": "",
        "InvoiceToID": "",
        "OPGCode": "",
        "ProductLines": "",
        "SalesOrg": "",
        "SalesRep": "",
        "SiebelAgentID": "",
        "ShipToID": "",
        "ShipToZip": "",
        "SoldToID": "",
        "SpecialCodes": "",
        "SupplierOrigSO": "",
        "SupplierMfgSO": "",
        "TeamID": "",
        "CampaignCode": "",
        "FunnelID": "",
        "CatalogID": "",
        "DistribChannel": "",
        "CommercialityCode": "",
        "PaymentMethod": {
            "CreditCard": "CreditCard - Credit Card Payment",
            "PayPal": "PayPal - PayPal Payment",
            "Wire": "Wire - Wire",
            "PAID": "PAID - Paid",
            "Check": "Check - Cheque Payment",
            "DirectDeposit": "DirectDeposit - Direct Deposit",
            "OperatorCredit": "OperatorCredit - Operator Credit",
            "CreditCardInstallments": "CreditCardInstallments - Credit Card Installments",
            "PayrollDeduction": "PayrollDeduction - Payroll Deduction",
            "PostPayment": "PostPayment - Post Payment",
            "NT15": "NT15 - NT15",
            "NS30": "NS30 - NS30",
            "NB15": "NB15 - NB15",
            "ZLES": "ZLES - ZLES",
            "ZILS": "ZILS - ZILS",
            "Lease": "Lease - Lease",
            "OpenInvoice": "OpenInvoice - Open Invoice",
            "PO": "PO - Postal Order",
            "Unknown": "Unknown - Others"
        },
        "CommunityID": "",
        "TelewebAgentID": "",
        "LogisticServiceProviderID": "",
        "PlantOrigSO": "",
        "PlantMfgSO": ""
    },
    "SearchByLocationType": {
        "OMRegion": {
            "APJ": "Asia Pacific",
            "EMEA": "European Region",
            "LA": "Latin America",
            "US": "United States",
            "CA": "Canada",
            "AMS": "North America"
        },
        "ShipToCountry": ""
    }
}

module.exports.ExtAdvSrch = {
    "OrderStatus": {
        "all": "All",
        "notship": "Not Shipped",
        "notdelv": "Not Delivered",
        "submit": "Submitted",
        "admin": "Admin",
        "prod": "Production",
        "proddone": "Production Done",
        "cons": "Consolidation",
        "ship": "Shipped",
        "delv": "Delivered",
        "canc": "Canceled",
        "ShipInvoiceStatus": {
            "n_ship": "Not Shipped",
            "pa_ship": "Partial Shipped",
            "fu_ship": "Fully Shipped",
            "n_inv": "Not Invoiced",
            "pa_inv": "Partial Invoiced",
            "fu_inv": "Fully Invoiced"
        },
        "CumulativeStatus": {
            "a_admin": "Admin (header)",
            "a_prod": "Production (header)",
            "a_cons": "Consolidation (header)",
            "a_ship": "Shipped (header)",
            "a_delv": "Delivered (header)"
        }
    },
    "RefContract": {
        "quote": "Quote#",
        "deal": "Deal ID",
        "claim": "eClaim#",
        "weborder": "Web Order#",
        "salno": "SAL#",
        "opg": "OPG Code"
    }
}
