var OMSOP = ''
module.exports.ShipHoldsText = {

    OP:       "OMS/PIM hold flag",
    MA:       "manuall handling flag on OMS/PIM",
    EXP:      "export Licence hold on OMS/PIM",
    PIA:      "payment in Advance Flag on OMS/PIM",
    CU:       "customer hold on OMS/PIM",
    'OMS-OP':   "OMS/PIM hold flag",
    'OMS-MA':   "manuall handling flag on OMS/PIM",
    'OMS-EXP':  "export Licence hold on OMS/PIM",
    'OMS-CR':   "credit hold on OMS",
    'OMS-PIA':  "payment in Advance Flag on OMS/PIM",
    'OMS-CU':   "customer hold on OMS/PIM",

};

module.exports.CreditHoldsText ={

    CR:       "credit hold on OMS",
    'OMS-CR':   "credit hold on OMS",
    'VISTA-CR-H': "Vista credit hold",
    'VISTA-CR-P': "Vista credit pending",
    'SAP-CRE':    "SAP sales office credit hold",
    'SAP-CRED':   "SAP credit shipment block",
    'SAP-CRER':  "SAP waiting credit approval",
};



module.exports.CatNames = {

    bill:     "Billing",
    can:     "Cancel",
    ff:       "Factory Fulfillment",
    fo:       "Fall Out",
    hide:     "Hide",
    info:     "Informational",
    oe:       "Order Entry",
    ship:     "Shipping",
    st:       "Status",
    bb:       "Blood Build",
    mr:       "Material Reservation",
    unknown:  "Unknown",
};

module.exports.SubCatNames = {
    acc:      "Account",
    alli:     "Alliance Hold",
    alloc:    "Allocation Issue",
    awcf:     "Awaiting Config Check",
    awcr:     "Awaiting Credit",
    awrp:     "Awaiting Release to Production",
    bitf:     "Bitfone Order",
    can:      "Cancel",
    cfg:      "Configuration",
    chg:      "Change",
    cins:     "Customer Inspection",
    cmov:     "Customer MOV (Min Order Value)",
    cons:     "Consolidated Delivery Hold",
    cont:     "Contract",
    cr:       "Credit",
    cred:     "Credit Reload",
    crp:      "Customer Road Permit",
    cust:     "Customer",
    data:     "Data Setup Error",
    deal:     "Deal",
    doc:      "Missing Doc",
    dpri:     "Deal Pricing",
    dupo:     "Duplicate PO",
    eord:     "eOrder Auto Hold",
    esc1:     "Escalate/Expedite Lev. 1",
    esc2:     "Escalate/Expedite Lev. 2",
    esc3:     "Escalate/Expedite Lev. 3",
    exp:      "Export Hold",
    fact:     "Factory Hold",
    ffw:      "FF WIP",
    fo:       "Fallout",
    fulcr:    "Fulfillment Credit",
    info:     "Missing Info",
    inv:      "Invoice",
    leas:     "Leasing Issue",
    lic:      "License / RPL Issue",
    man:      "Manual Hold",
    mat:      "Material",
    mer:      "Merge",
    npi:      "NPI",
    obs:      "Obsolete Product",
    oee:      "Order Entry Error",
    oew:      "OE WIP",
    ois:      "OIS Fallout",
    oth:      "Other",
    part:     "Partial Invoice",
    pay:      "Payment / Cash in Advance",
    plant:    "Plant Issue",
    pri:      "Pricing",
    prod:     "Product Hold",
    pro:      "Product",
    res:      "Reservation Order",
    sap:      "SAP",
    sch:      "Scheduled",
    serv:     "Services",
    ship:     "Ship Hold",
    shipm:    "Shipment Hold",
    shto:     "Ship To Issues",
    shw:      "Ship WIP",
    skel:     "Skeleton Order",
    so:       "Sales Office Hold",
    stax:     "Tax Hold, T&Cs",
    supp:     "Supplier Info Issue",
    tba:      "TBA",
    tra:      "Traffic",
    uns:      "Unschedule",
    vdps:     "VDPS Order"

}
module.exports.constants = {
    MAX_NUM_ROWS: "1000",
}

module.exports.countryName = {
    AT: "Austria",
    CH: "Switzerland",
    BE: "Belgium",
    ES: "Spain",
    EU: "Europe",
    FI: "Finland",
    FR: "France",
    GB: "United Kingdom",
    GR: "Greece",
    HU: "Hungary",
    IE: "Ireland",
    IL: "Israel",
    GZ: "Gaza Strip",
    IR: "Iran",
    NL: "Netherlands",
    NO: "Norway",
    PL: "Poland",
    PT: "Portugal",
    RU: "Russia",
    SA: "Saudi Arabia",
    SE: "Sweden",
    SI: "Slovenia",
    TR: "Turkey",
    AM: "Armenia",
    BY: "Belarus",
    BG: "Bulgaria",
    HR: "Croatia",
    CY: "Cyprus",
    EG: "Egypt",
    GE: "Georgia",
    KZ: "Kazakhstan",
    KG: "Kyrgyzstan",
    LV: "Latvia",
    LB: "Lebanon",
    MT: "Malta",
    MD: "Moldova",
    MN: "Mongolia",
    MA: "Morocco",
    NG: "Nigeria",
    GH: "Ghana",
    GA: "Gabon",
    SN: "Senegal",
    LR: "Liberia",
    OM: "Oman",
    RO: "Romania",
    SK: "Slovakia",
    ZA: "South Africa",
    TJ: "Tajikistan",
    TN: "Tunisia",
    UA: "Ukraine",
    US: "United States",
    UZ: "Uzbekistan",
    VE: "Venezuela",
    YE: "Yemen",
    AE: "United Arab Emirates",
    KW: "Kuwait",
    LI: "Liechtenstein",
    FO: "Faroe Islands",
    LT: "Lithuania",
    NA: "Namibia",
    KE: "Kenya",
    QA: "Qatar",
    GF: "French Guyana",
    YU: "Yugoslavia",
    AU: "Australia",
    GP: "Guadeloupe",
    CE: "Eastern Countries",
    ND: "Nordic Countries",
    CF: "Central African Republic",
    LS: "Lesotho",
    LU: "Luxembourg",
    MW: "Malawi",
    MQ: "Martinique",
    MZ: "Mozambique",
    RE: "Reunion",
    TZ: "Tanzania",
    SZ: "Swaziland",
    UG: "Uganda",
    ZM: "Zambia",
    MU: "Mauritius",
    ZW: "Zimbabwe",
    CM: "Cameroon",
    GL: "Greenland",
    ZR: "Zaire",
    ML: "Mali",
    BJ: "Benin",
    CG: "Congo",
    NE: "Niger",
    PF: "French Polynesia",
    TF: "French Southern Territories",
    BC: "Baltic",
    KH: "Cambodia",
    TW: "Taiwan",
    AC: "Middle East",
    WA: "North West Africa",
    KN: "St. Kitts and Nevis",
    WF: "Wallis and Futuna",
    MC: "Monaco",
    YT: "Mayotte",
    NF: "Norfolk Island",
    CC: "Cocos (Keeling) Islands",
    CX: "Christmas Islands",
    HM: "Heard & McDonald Islands",
    CK: "Cook Islands",
    TK: "Tokelau",
    NU: "Niue",
    VU: "Vanuatu",
    PN: "Pitcairn Island",
    CT:"Kiribati",
    MV: "Maledive Islands",
    ER: "Eritrea",
    DM: "Dominica",
    MS: "Montserrat",
    LC: "Saint Lucia",
    FJ: "Fiji",
    TO: "Tonga",
    GW: "Guinea-Bisseau",
    ST: "Sao Tome and Principe",
    TV: "Tuvalu",
    SM: "San Marino",
    VA: "Vatican City",
    US: "United States",
    CA: "Canada",
    PM: "St. Pierre and Miquelon",
    BZ: "Belize",
    SV: "El Salvador",
    HN: "Honduras",
    CR: "Costa Rica",
    PA: "Panama",
    BM: "Bermuda",
    CU: "Cuba",
    JM: "Jamaica",
    KY: "Cayman Island",
    HT: "Haiti",
    DO: "Dominican Republic",
    BB: "Barbados",
    TT: "Trinidad and Tobago",
    AN: "Netherlands Antilles",
    GY: "Guyana",
    SR: "Suriname",
    EC: "Ecuador",
    BO: "Bolivia",
    CL: "Chile",
    UY: "Uruguay",
    PT:    "Azores",
    GI: "Gibraltar",
    IN: "India",
    PK: "Pakistan",
    ME: "Montenegro",
    RS: "Serbia",
    NP: "Nepal",
    BD: "Bangladesh",
    LK: "Sri Lanka",
    BU: "Burma",
    TH: "Thailand",
    VN: "Vietnam",
    LA: "Laos",
    MY: "Malaysia",
    SG: "Singapore",
    ID: "Indonesia",
    BN: "Brunei",
    PH: "Philippines",
    MO: "Macao",
    BT: "Bhutan",
    CN: "China, Peoples Republic",
    KP: "North Korea",
    KR: "Korea, Republic of (South)",
    HK: "Hong Kong",
    JP: "Japan",
    SS: "South Sudan",
    PG: "Papua New Guinea",
    NZ: "New Zealand",
    WS: "Western Samoa",
    SB: "Solomon Islands",
    MH: "Marshall Islands",
    FM: "Micronesia, Fed. States of",
    PW: "Palau",
    PC: "Trust Terr. of Pacific Islands",
    NR: "Nauru",
    LY: "Libya",
    SD: "Sudan",
    CT:    "Canary Islands",
    CW: "Curaco",
    EH: "Western Sahara",
    GQ: "Equatorial Guinea",
    MR: "Mauritania",
    GN: "Guinea",
    SL: "Sierra Leone",
    GM: "Gambia",
    TG: "Togo",
    TD: "Chad",
    SH: "St. Helena",
    PT:    "Madeira Islands",
    BF: "Burkina Faso",
    CV: "Cape Verde",
    BI: "Burundi",
    RW: "Rwanda",
    SO: "Somalia",
    ET: "Ethiopia",
    DJ: "Djibouti",
    SC: "Seychelles",
    IO: "British Indian Ocean Terr.",
    KM: "Comoros",
    PR: "Puerto Rico",
    VI: "Virgin Islands of the US",
    MI: "Midway Island",
    WK: "Wake Island",
    GU: "Guam",
    CT: "Canton & Enderbury Islands",
    AS: "American Samoa",
    MP: "Northern Mariana Islands",
    IQ: "Iraq",
    MG: "Madagascar",
    MM: "Myanmar (Burma)",
    SY: "Syria",
    TP: "East Timor",
    DE: "Germany",
    EE: "Estonia",
    IS: "Iceland",
    MX: "Mexico",
    BR: "Brazil",
    NA: "Unknown",
    RET:"Returns",
    DIR:"DirectShip",
    AD: "Andorra",
    AO: "Angola",
    AI: "Anguilla",
    AG: "Antigua and Barbura",
    AR: "Argentina",
    AW: "Aruba",
    BS: "Bahamas",
    AF: "Afghanistan",
    AL: "Albania",
    DZ: "Algeria",
    PS: "Palestinian Territory, Occupied",
    AZ: "Azerbaijan",
    BH: "Bahrain",
    BA: "Bosnia-Herzegovina",
    BW: "Botswana",
    CO: "Colombia",
    CZ: "Czech Republic",
    DK: "Denmark",
    FK: "Falkland Islands",
    GT: "Guatemala",
    GG: "Guernsey, Channel Islands",
    IT: "Italy",
    CI: "Ivory Coast",
    LU: "Luxembourg",
    MK: "Macedonia (Former Yugoslav Rep)",
    NI: "Nicaragua",
    PY: "Paraguay",
    PE: "Peru",
    VC: "St. Vincent & Grenadines",
    SJ: "Svalbard and Jan Mayen",
    TM: "Turkmenistan",
    TC: "Turks and Caicos Islands",
    VG: "Virgin Islands, British",
    CS: "Serbia and Montenegro",
    GD: "Grenada",
    NC: "New Caledonia",
    JO: "Jordan",
    DJ: "Djibouti",
    MEA:    "Middle East and South Africa",
    SS: "South Sudan",
    UM: "United States Minor Outlying Islands"

}
