/*----------------------------------------------------------------------------
|
|   Config file for Data Maintain Tools.
|
|
|   written for opt/oss/pkg/frontend/OSfInternalUIServer
|   written by Alok Upendra Kamat
|   August 2013
|
\---------------------------------------------------------------------------*/

module.exports = {

    "Billing Block Setup": {
        "table_name": "BILLING_BLOCK_SETUP",
        "count_button": "Y",
        "select_button": "Y",
        "insert_button": "N",
        "update_button": "Y",
        "delete_button": "N",
        "user_locked": "N",
        "allowed_insert_grp": "",
        "allowed_update_grp": "",
        "allowed_delete_grp": "",
        "description": "",
        "wiki_link": "",
        "column_labels": {
            "SAPSYSTEM": "SAP System",
            "BILLING_BLOCK": "Billing Block",
            "BILLING_BLOCK_TEXT": "Billing Block Text",
            "BLOCK_CATEGORY": "Classification",
            "EXTERNAL_TEXT": "OrderStatus Text",
            "INTERNAL_TEXT": "SANDY Text",
            "RECORD_STATE": "Record State"
        },
        "predefined_values": {
            "BLOCK_CATEGORY": {
                "hide": "Hide",
                "info": "Informational",
                "oe/cr": "Order Entry - Credit",
                "oe/cfg": "Order Entry - Configuration",
                "oe/doc": "Order Entry - Missing Doc",
                "oe/info": "Order Entry - Missing Info",
                "oe/pri": "Order Entry - Pricing",
                "oe/pro": "Order Entry - Product",
                "oe/stax": "Order Entry - Tax Hold, T&Cs",
                "oe/acc": "Order Entry - Account",
                "oe/bitf": "Order Entry - Bitfone Order",
                "oe/cont": "Order Entry - Contract",
                "oe/cust": "Order Entry - Customer",
                "oe/cins": "Order Entry - Customer Inspection Hold",
                "oe/cmov": "Order Entry - Customer MOV (Min Order Value)",
                "oe/crp": "Order Entry - Customer Road Permit",
                "oe/data": "Order Entry - Data Setup Error",
                "oe/deal": "Order Entry - Deal",
                "oe/dpri": "Order Entry - Deal Pricing",
                "oe/dupo": "Order Entry - Duplicate PO Hold",
                "oe/eord": "Order Entry - eOrder Auto Hold",
                "oe/fulcr": "Order Entry - Fulfillment Credit Hold",
                "oe/leas": "Order Entry - Leasing Issue",
                "oe/lic": "Order Entry - License / RPL Issue",
                "oe/man": "Order Entry - Manual Hold",
                "oe/ois": "Order Entry - OIS Fallout",
                "oe/oee": "Order Entry - Order Entry Error",
                "oe/pay": "Order Entry - Payment / Cash in Advance",
                "oe/res": "Order Entry - Reservation Order",
                "oe/so": "Order Entry - Sales Office Hold",
                "oe/serv": "Order Entry - Services",
                "oe/ship": "Order Entry - Ship Hold",
                "oe/shto": "Order Entry - Ship To Issue",
                "oe/skel": "Order Entry - Skeleton Order",
                "oe/supp": "Order Entry - Supplier Info Issue",
                "oe/vdps": "Order Entry - VDPS Order",
                "oe/oth": "Order Entry - Other",
                "ff/cfg": "Factory Fulfillment - Configuration",
                "ff/doc": "Factory Fulfillment - Missing Doc",
                "ff/mat": "Factory Fulfillment - Material",
                "ff/chg": "Factory Fulfillment - Change",
                "ff/uns": "Factory Fulfillment - Unschedule",
                "ff/cons": "Factory Fulfillment - Consolidated Delivery Hold",
                "ff/alli": "Factory Fulfillment - Alliance Hold",
                "ff/alloc": "Factory Fulfillment - Allocation Issue",
                "ff/cred": "Factory Fulfillment - Credit Reload",
                "ff/esc1": "Factory Fulfillment - Escalation / Expedite Lev. 1",
                "ff/esc2": "Factory Fulfillment - Escalation / Expedite Lev. 2",
                "ff/esc3": "Factory Fulfillment - Escalation / Expedite Lev. 3",
                "ff/fact": "Factory Fulfillment - Factory Hold",
                "ff/exp": "Factory Fulfillment - Export Hold",
                "ff/npi": "Factory Fulfillment - NPI",
                "ff/obs": "Factory Fulfillment - Obsolete Product",
                "ff/plant": "Factory Fulfillment - Plant Issue",
                "ff/prod": "Factory Fulfillment - Product Hold",
                "ff/shipm": "Factory Fulfillment - Shipment Hold",
                "ff/tba": "Factory Fulfillment - TBA",
                "ff/oth": "Factory Fulfillment - Other",
                "ship/tra": "Shipping - Traffic",
                "ship/mer": "Shipping - Merge",
                "ship/sch": "Shipping - Scheduled",
                "ship/fo": "Shipping - Fallout",
                "ship": "Shipping - Other",
                "bill/inv": "Billing - Invoice",
                "bill/part": "Billing - Partial Invoice",
                "bill": "Billing - Other",
                "st/awcf": "Status - Awaiting Config Check",
                "st/awcr": "Status - Awaiting Credit",
                "st/awrp": "Status - Awaiting Release to Production",
                "st/ffw": "Status - FF WIP",
                "st/oew": "Status - OE WIP",
                "st/shw": "Status - Ship WIP",
                "can": "Cancel"
            }
        }
    },
    "Carrier Setup": {
        "table_name": "CARRIER",
        "count_button": "Y",
        "select_button": "Y",
        "insert_button": "Y",
        "update_button": "Y",
        "delete_button": "Y",
        "user_locked": "N",
        "allowed_insert_grp": "",
        "allowed_update_grp": "",
        "allowed_delete_grp": "",
        "description": "",
        "wiki_link": "",
        "column_labels": {
            "CARRIER_ID": "Carrier Id",
            "CARRIER_CODE": "Carrier Code",
            "CARRIERNAME": "Carrier Name",
            "CARRIER_ADDRESS": "Carrier Address",
            "CITY_NAME": "City Name",
            "ZIP_CODE": "Zip Code",
            "ISO_COUNTRY": "ISO Country",
            "SCAC": "Scac",
            "USID": "US Id",
            "EUROPEID": "Europe Id",
            "COMID": "COM Id",
            "EICID": "EIC Id",
            "ISTRACKANDTRACE": "Is Track And Trace",
            "ISPODIMAGE": "Is Podimage",
            "UNIQUE_CODE": "Unique Code",
            "APID": "AP Id"
        },
        "predefined_values": {}
    },
    "Country Code Setup": {
        "table_name": "COUNTRY",
        "count_button": "Y",
        "select_button": "Y",
        "insert_button": "Y",
        "update_button": "Y",
        "delete_button": "Y",
        "user_locked": "N",
        "allowed_insert_grp": "",
        "allowed_update_grp": "",
        "allowed_delete_grp": "",
        "description": "",
        "wiki_link": "",
        "column_labels": {
            "COUNTRY_NAME": "Country Name",
            "ISO_CODE": "ISO Code",
            "HP_CODE": "HP Code",
            "REGION": "Common Region",
            "SUBREGION": "HP Subregion",
            "IN_BACKLOG_SHIP": "In Backlog Ship",
            "ISO3_CODE": "ISO3 Code",
            "HP_REGION": "HP Region"
        },
        "predefined_values": {
            "HP_REGION": {
                "": "empty",
                "NA": "NA",
                "LAR": "LAR",
                "EMEA": "EMEA",
                "APJ": "APJ"
            }
        }
    },
    "Country Dimension Setup": {
        "table_name": "COUNTRY_DIM",
        "count_button": "Y",
        "select_button": "Y",
        "insert_button": "Y",
        "update_button": "Y",
        "delete_button": "Y",
        "user_locked": "N",
        "allowed_insert_grp": "",
        "allowed_update_grp": "",
        "allowed_delete_grp": "",
        "description": "",
        "wiki_link": "",
        "column_labels": {
            "COUNTRY_ID": "Country Id",
            "GROUPING1": "Grouping 1",
            "GROUPING2": "Grouping 2",
            "GROUPING3": "Grouping 3",
            "COUNTRY": "Country",
            "SUB_COUNTRY": "Sub Country",
            "ORDER_PREFIX": "Order Prefix"
        },
        "predefined_values": {}
    },
    "Setup SSM Codes for Delivery Comments": {
        "table_name": "SHIPMENT_COMMENTS_SSM",
        "count_button": "Y",
        "select_button": "Y",
        "insert_button": "N",
        "update_button": "N",
        "delete_button": "N",
        "user_locked": "Y",
        "allowed_insert_grp": "cap:CommitRulesAdmin:insert",
        "allowed_update_grp": "cap:CommitRulesAdmin:update",
        "allowed_delete_grp": "cap:CommitRulesAdmin:delete",
        "description": "This table allows to set up which SSM Codes should be shown in Sandy as delivery comments",
        "wiki_link": "",
        "column_labels": {
            "CARRIER_STATUS_CODE": "Status Code",
            "CARRIER_STATUS_DESCR": "Description",
            "CARRIER_STATUS_REASON_CODE": "Reason Code",
            "CARRIER_STATUS_COMMENT": "Comment in SANDY",
            "DISPLAY_FLAG": "Show in SANDY?"
        },
        "predefined_values": {
            "DISPLAY_FLAG": {
                "Y": "Y",
                "N": "N"
            }
        }
    },
    "Price Condition Flags": {
        "table_name": "PRICE_CONDITION_FLAGS",
        "count_button": "N",
        "select_button": "Y",
        "insert_button": "N",
        "update_button": "N",
        "delete_button": "N",
        "user_locked": "Y",
        "allowed_insert_grp": "cap:PriceConditionFlags:insert",
        "allowed_update_grp": "cap:PriceConditionFlags:update",
        "allowed_delete_grp": "cap:PriceConditionFlags:delete",
        "description": "",
        "wiki_link": "http://ossws-tst.corp.hp.com:8888/IndexScreens/PriceConditionFlags/",
        "column_labels": {
            "SOURCE_SYSTEM": "SAP System",
            "PRICE_CONDITION": "Price Condition",
            "ROLLUP_TO_LIST_PRICE": "Rollup to List Price",
            "PRICE_PROTECTION": "Price Protection",
            "VISIBLE": "Visible",
            "RECORD_STATE": "State",
            "SHOW_WITH_DEAL_NUM": "Display Deal No."
        },
        "predefined_values": {
            "ROLLUP_TO_LIST_PRICE": {
                "Y": "Y",
                "N": "N"
            },
            "PRICE_PROTECTION": {
                "Y": "Y",
                "N": "N"
            },
            "VISIBLE": {
                "Y": "Y",
                "N": "N"
            },
            "SHOW_WITH_DEAL_NUM": {
                "Y": "Y",
                "N": "N"
            },
            "RECORD_STATE": {
                "ACTIVE": "ACTIVE",
                "": ""
            }
        }
    },
    "Price Condition Texts": {
        "table_name": "PRICE_CONDITION_TEXTS",
        "count_button": "N",
        "select_button": "Y",
        "insert_button": "N",
        "update_button": "N",
        "delete_button": "N",
        "user_locked": "Y",
        "allowed_insert_grp": "cap:PriceConditionTexts:insert",
        "allowed_update_grp": "cap:PriceConditionTexts:update",
        "allowed_delete_grp": "cap:PriceConditionTexts:delete",
        "description": "",
        "wiki_link": "http://ossws-tst.corp.hp.com:8888/IndexScreens/PriceConditionTexts/",
        "column_labels": {
            "SOURCE_SYSTEM": "SAP System",
            "PRICE_CONDITION": "Price Condition",
            "LANGUAGE_CODE": "Language Code",
            "ORIGINAL_TEXT": "SAP Text",
            "OVERRIDE_TEXT": "Override Text",
            "RECORD_STATE": "State"
        },
        "predefined_values": {
            "RECORD_STATE": {
                "ACTIVE": "ACTIVE",
                "": ""
            }
        }
    },
    "Product Line Dimension Setup": {
        "table_name": "PL_DIM",
        "count_button": "Y",
        "select_button": "Y",
        "insert_button": "Y",
        "update_button": "Y",
        "delete_button": "Y",
        "user_locked": "N",
        "allowed_insert_grp": "",
        "allowed_update_grp": "",
        "allowed_delete_grp": "",
        "description": "",
        "wiki_link": "",
        "column_labels": {
            "GROUP_NAME": "Group Name",
            "GROUP_NAME_ID": "Group Name Id",
            "GROUP_NAME_SHORT": "Group Name Short",
            "GROUP_CODE": "Group Code",
            "GROUP_CODE_ID": "Group Code Id",
            "CATEGORY_NAME": "Category Name",
            "CATEGORY_ID": "Category Id",
            "CATEGORY_SHORT": "Category Short",
            "LINE": "Line",
            "LINE_NAME": "Line Name",
            "PRIO": "Prio"
        },
        "predefined_values": {}
    },
    "PlannedCustomerShipDate Filter Set Up": {
        "table_name": "COMMIT_RULE_OPERATIONAL",
        "count_button": "Y",
        "select_button": "Y",
        "insert_button": "N",
        "update_button": "N",
        "delete_button": "N",
        "user_locked": "Y",
        "allowed_insert_grp": "cap:CommitRulesAdmin:insert",
        "allowed_update_grp": "cap:CommitRulesAdmin:update",
        "allowed_delete_grp": "cap:CommitRulesAdmin:delete",
        "description": "This filter is used to determine automatically how the planned customer shipment date and subsequently the planned customer delivery date are being updated: - What is the delay from the order creation date we want to start to communicate to our customers e.g. wait 24 hour before communicating anything despite a Planned factory shipment date already exists. - If a planned factory ship date has changed is the change significant enough to update our customers with. o A window in days before and days after the last communicated shipment date is determined to filter out all non-significant changes o This leads to have a planned factory shipment date different from the planned customer ship date.",
        "wiki_link": "http://ossws-tst.corp.hp.com:8888/IndexScreens/OperationalSetup",
        "column_labels": {
            "OM_REGION": "Region",
            "OM_SYSTEM": "Originating System",
            "SALES_ORG": "Sales Org",
            "RTM": "Road To Market",
            "BT": "Business Type",
            "SEGMENT": "Customer Segment",
            "SUB_SEGMENT": "Customer Sub Segment",
            "MSM": "MSM",
            "ORDERLOADWINDOW": "Order Load Time Window",
            "REACKLOWER": "REACK Lower Time Window",
            "REACKUPPER": "REACK Upper Time Window",
            "BUFFERDAYS": "Buffer Days"
        },
        "predefined_values": {
            "OM_REGION": {
                "APJ": "APJ",
                "CA": "CA",
                "EMEA": "EMEA",
                "LA": "LA",
                "US": "US"
            },
            "RTM": {
                "D": "Direct",
                "I": "Indirect",
                "*": "*"
            },
            "BT": {
                "O": "Volume",
                "A": "Value",
                "K": "Kiosk",
                "*": "*"
            },
            "SEGMENT": {
                "Business": "Business",
                "Commercial": "Commercial",
                "Consumer": "Consumer",
                "Corp/Ent": "Corp/Ent",
                "DNA": "DNA",
                "GlobalAccount": "GlobalAccount",
                "Other": "Other",
                "PartnerDirect": "PartnerDirect",
                "PublicSector": "PublicSector",
                "SMB": "SMB",
                "Supplies": "Supplies",
                "*": "*"
            },
            "SUB_SEGMENT": {
                "AgentDirect": "AgentDirect",
                "Club": "Club",
                "DirectDirect": "DirectDirect",
                "ExternalEPP": "ExternalEPP",
                "FriendsAndFamily": "FriendsAndFamily",
                "InternalEPP": "InternalEPP",
                "PartnerDirect": "PartnerDirect",
                "Private": "Private",
                "Public": "Public",
                "Student": "Student",
                "ebay": "ebay",
                "*": "*"
            },
            "MSM": {
                "APOrderDesk": "APOrderDesk",
                "Corp_Reseller/W3": "Corp_ResellerW3",
                "DMFI": "DMFI",
                "E-Store": "E-Store",
                "FOB": "FOB",
                "Genesis": "Genesis",
                "IndiaDGSND": "IndiaDGSND",
                "JapanOEM": "JapanOEM",
                "JapanOrderDesk": "JapanOrderDesk",
                "Kiosk": "Kiosk",
                "LAPartnerDirect": "LAPartnerDirect",
                "LAVolumeSales": "LAVolumeSales",
                "LocalIndirect": "LocalIndirect",
                "Remarketing": "Remarketing",
                "Retailer/W2": "Retailer/W2",
                "SBSO": "SBSO",
                "BBTO": "BBTO",
                "Standard": "Standard",
                "TopConfig": "TopConfig",
                "TopValue": "TopValue",
                "US-VDO_exclusion": "US-VDO_exclusion",
                "WholeSeller/W1": "WholeSeller/W1",
                "*": "*"
            }
        }
    },
    "Fallout Code Setup": {
        "table_name": "FALLOUT_CODES",
        "count_button": "Y",
        "select_button": "Y",
        "insert_button": "N",
        "update_button": "Y",
        "delete_button": "N",
        "user_locked": "N",
        "allowed_insert_grp": "",
        "allowed_update_grp": "",
        "allowed_delete_grp": "",
        "description": "",
        "wiki_link": "",
        "column_labels": {
            "SAPSYSTEM": "System",
            "CODE": "Code",
            "CODE_TEXT": "Code Text",
            "INTERNAL_TEXT": "SANDY Text"
        },
        "predefined_values": {}
    },
    "Material Status Setup": {
        "table_name": "MAT_STATUS_SETUP",
        "count_button": "Y",
        "select_button": "Y",
        "insert_button": "N",
        "update_button": "Y",
        "delete_button": "N",
        "user_locked": "N",
        "allowed_insert_grp": "",
        "allowed_update_grp": "",
        "allowed_delete_grp": "",
        "description": "",
        "wiki_link": "",
        "column_labels": {
            "MATERIAL_STATUS": "Material Status",
            "MATERIAL_STATUS_TEXT": "Material Status Text",
            "INTERNAL_TEXT": "SANDY Text",
            "BLOCK_CATEGORY": "Classification",
            "EXTERNAL_TEXT": "OrderStatus Text",
            "RECORD_STATE": "Record State"
        },
        "predefined_values": {
            "BLOCK_CATEGORY": {
                "hide": "Hide",
                "info": "Informational",
                "oe/cr": "Order Entry - Credit",
                "oe/cfg": "Order Entry - Configuration",
                "oe/doc": "Order Entry - Missing Doc",
                "oe/info": "Order Entry - Missing Info",
                "oe/pri": "Order Entry - Pricing",
                "oe/pro": "Order Entry - Product",
                "oe/stax": "Order Entry - Tax Hold, T&Cs",
                "oe/acc": "Order Entry - Account",
                "oe/bitf": "Order Entry - Bitfone Order",
                "oe/cont": "Order Entry - Contract",
                "oe/cust": "Order Entry - Customer",
                "oe/cins": "Order Entry - Customer Inspection Hold",
                "oe/cmov": "Order Entry - Customer MOV (Min Order Value)",
                "oe/crp": "Order Entry - Customer Road Permit",
                "oe/data": "Order Entry - Data Setup Error",
                "oe/deal": "Order Entry - Deal",
                "oe/dpri": "Order Entry - Deal Pricing",
                "oe/dupo": "Order Entry - Duplicate PO Hold",
                "oe/eord": "Order Entry - eOrder Auto Hold",
                "oe/fulcr": "Order Entry - Fulfillment Credit Hold",
                "oe/leas": "Order Entry - Leasing Issue",
                "oe/lic": "Order Entry - License / RPL Issue",
                "oe/man": "Order Entry - Manual Hold",
                "oe/ois": "Order Entry - OIS Fallout",
                "oe/oee": "Order Entry - Order Entry Error",
                "oe/pay": "Order Entry - Payment / Cash in Advance",
                "oe/res": "Order Entry - Reservation Order",
                "oe/so": "Order Entry - Sales Office Hold",
                "oe/serv": "Order Entry - Services",
                "oe/ship": "Order Entry - Ship Hold",
                "oe/shto": "Order Entry - Ship To Issue",
                "oe/skel": "Order Entry - Skeleton Order",
                "oe/supp": "Order Entry - Supplier Info Issue",
                "oe/vdps": "Order Entry - VDPS Order",
                "oe/oth": "Order Entry - Other",
                "ff/cfg": "Factory Fulfillment - Configuration",
                "ff/doc": "Factory Fulfillment - Missing Doc",
                "ff/mat": "Factory Fulfillment - Material",
                "ff/chg": "Factory Fulfillment - Change",
                "ff/uns": "Factory Fulfillment - Unschedule",
                "ff/cons": "Factory Fulfillment - Consolidated Delivery Hold",
                "ff/alli": "Factory Fulfillment - Alliance Hold",
                "ff/alloc": "Factory Fulfillment - Allocation Issue",
                "ff/cred": "Factory Fulfillment - Credit Reload",
                "ff/esc1": "Factory Fulfillment - Escalation / Expedite Lev. 1",
                "ff/esc2": "Factory Fulfillment - Escalation / Expedite Lev. 2",
                "ff/esc3": "Factory Fulfillment - Escalation / Expedite Lev. 3",
                "ff/fact": "Factory Fulfillment - Factory Hold",
                "ff/exp": "Factory Fulfillment - Export Hold",
                "ff/npi": "Factory Fulfillment - NPI",
                "ff/obs": "Factory Fulfillment - Obsolete Product",
                "ff/plant": "Factory Fulfillment - Plant Issue",
                "ff/prod": "Factory Fulfillment - Product Hold",
                "ff/shipm": "Factory Fulfillment - Shipment Hold",
                "ff/tba": "Factory Fulfillment - TBA",
                "ff/oth": "Factory Fulfillment - Other",
                "ship/tra": "Shipping - Traffic",
                "ship/mer": "Shipping - Merge",
                "ship/sch": "Shipping - Scheduled",
                "ship/fo": "Shipping - Fallout",
                "ship": "Shipping - Ohter",
                "bill/inv": "Billing - Invoice",
                "bill/part": "Billing - Partial Invoice",
                "bill": "Billing - Other ",
                "st/awcf": "Status - Awaiting Config Check",
                "st/awcr": "Status - Awaiting Credit",
                "st/awrp": "Status - Awaiting Release to Production",
                "st/ffw": "Status - FF WIP",
                "st/oew": "Status - OE WIP",
                "st/shw": "Status - Ship WIP",
                "can": "Cancel"
            }
        }
    },
    "Organization / Account Setup": {
        "table_name": "ORG_RELATION",
        "count_button": "Y",
        "select_button": "Y",
        "insert_button": "Y",
        "update_button": "Y",
        "delete_button": "Y",
        "user_locked": "N",
        "allowed_insert_grp": "",
        "allowed_update_grp": "",
        "allowed_delete_grp": "",
        "description": "",
        "wiki_link": "",
        "column_labels": {
            "OM_REGION": "OM Region",
            "BUSINESS_TYPE": "Business Type",
            "RTM": "RTM",
            "CUSTOMER_SEGMENT": "Costumer Segment",
            "KEY": "Key",
            "VALUE": "Value",
            "ACCOUNT": "Account",
            "FO_NAME": "FO Name",
            "FO_TEAM": "FO Team",
            "FO_MANAGER": "FO Manager",
            "FO_EMAIL": "FO Email",
            "ACCOUNT_MANAGER": "Account Manager",
            "ACCOUNT_GROUP_NAME": "Account Group Name",
            "ACCOUNT_COUNTRY": "Account Country",
            "ACCOUNT_SERVICE_LEVEL": "Account Service Level",
            "SALES_SUPPORT_NAME": "Sales Support Name",
            "SALES_SUPPORT_EMAIL": "Sales Support Email",
            "SALES_CONTACT_NAME": "Sales Contact Name",
            "SALES_CONTACT_EMAIL": "Sales Contact Email",
            "BUSINESS_MODEL": "Business Model",
            "BO_NAME": "BO Name",
            "BO_EMAIL": "BO Email"
        },
        "predefined_values": {
            "OM_REGION": {
                "US": "US",
                "EMEA": "EMEA",
                "APJ": "APJ",
                "LA": "LA"
            },
            "BUSINESS_TYPE": {
                "O": "Volume",
                "A": "Value"
            },
            "RTM": {
                "D": "Direct",
                "I": "Indirect"
            },
            "CUSTOMER_SEGMENT": {
                "Commercial": "Commercial",
                "Consumer": "Consumer",
                "COR": "COR",
                "Corp/Ent": "Corp/Ent",
                "Direct": "Direct",
                "DNA": "DNA",
                "EAB": "EAB",
                "EAL": "EAL",
                "EIQ": "EIQ",
                "ENT": "ENT",
                "EQC": "EQC",
                "EQI": "EQI",
                "ETR": "ETR",
                "FED": "FED",
                "GFD": "GFD",
                "GPS": "GPS",
                "HE1": "HE1",
                "HE2": "HE2",
                "KE1": "KE1",
                "KE2": "KE2",
                "LC1": "LC1",
                "LC2": "LC2",
                "MMC": "MMC",
                "Other": "Other",
                "PartnerDirect": "PartnerDirect",
                "PCS": "PCS",
                "PRT": "PRT",
                "PublicSector": "PublicSector",
                "SLED": "SLED",
                "SMB": "SMB",
                "ST1": "ST1",
                "ST2": "ST2",
                "Supplies": "Supplies"
            },
            "KEY": {
                "CBN": "CBN",
                "PA": "PA",
                "SoldToID": "SoldToID",
                "TeamID": "TeamID",
                "ShipToZone": "ShipToZone",
                "CustomerGroup": "CustomerGroup"
            }
        }
    },
    "SC CommitDate Filter Set Up": {
        "table_name": "COMMIT_RULE_SUPPLY_CHAIN",
        "count_button": "Y",
        "select_button": "Y",
        "insert_button": "N",
        "update_button": "N",
        "delete_button": "N",
        "user_locked": "Y",
        "allowed_insert_grp": "cap:CommitRulesAdmin:insert",
        "allowed_update_grp": "cap:CommitRulesAdmin:update",
        "allowed_delete_grp": "cap:CommitRulesAdmin:delete",
        "description": "A SC commit logic is used to filter out all dates coming from the SC we do not consider yet accurate enough to be further communicated to our customers. Filtering logic to be applied can be specific to a shipping point (Shipfrom) but as well a product #, a segment, a RTM, &. Once conditions are met the system updates the planned factory ship date field from the SC Commit date.",
        "wiki_link": "http://ossws-tst.corp.hp.com:8888/IndexScreens/OperationalSetup",
        "column_labels": {
            "RULE": "Rule Name",
            "SHIPPINGPOINT": "Shipping Point",
            "PRIORITY": "Priority",
            "PARAMETER": "Parameter",
            "OPERATION": "Operator",
            "VALUE": "Value",
            "TAKESOFTCOMMIT": "Take Soft Commit",
            "COMMITLOGIC": "Commit Logic",
            "FARAWAYTHRESHOLD": "Far Away threshold",
            "OMREGION": "OM Region"
        },
        "predefined_values": {
            "OPERATION": {
                "exclude": "exclude",
                "include": "include",
                "none": "none"
            },
            "PARAMETER": {
                "PN": "Product Number",
                "PL": "Product Line",
                "MSM": "MSM",
                "Supplier": "Supplier",
                "ItemCat": "Item Category",
                "PlantCode": "Plant Code",
                "SalesOrg": "Sales Org",
                "none": "none"
            },
            "TAKESOFTCOMMIT": {
                "Y": "Y",
                "N": "N"
            },
            "COMMITLOGIC": {
                "24HourLogic": "24H",
                "48HourLogic": "48H",
                "DelayLogic1Day": "Delay (1)",
                "DelayLogic2Day": "Delay (2)",
                "Drop&Chase1Day": "Drop&Chase (1)",
                "Drop&Chase2Day": "Drop&Chase (2)",
                "AllocationLogic": "Allocation",
                "OrderDropLogic": "Order Drop",
                "ScheduledOrders": "Scheduled Orders",
                "ODMCommit1Day": "ODM Commit 1 day",
                "ODMCommit2Day": "ODM Commit 2 days"
            },
            "OMREGION": {
                "US": "US",
                "LA": "LA",
                "CA": "CA",
                "EMEA": "EMEA",
                "APJ": "APJ",
                "All": "All"
            }
        }
    },
    "Corp Setup": {
        "table_name": "CORP_SETUP",
        "count_button": "Y",
        "select_button": "Y",
        "insert_button": "Y",
        "update_button": "Y",
        "delete_button": "Y",
        "user_locked": "N",
        "allowed_insert_grp": "",
        "allowed_update_grp": "",
        "allowed_delete_grp": "",
        "description": "",
        "wiki_link": "",
        "column_labels": {
            "CORP_NAME": "Corporation Name",
            "REGION": "Region",
            "LEVEL4NCRFS": "Level 4 Ncfrs",
            "OLDNCRFS": "Old Ncfrs",
            "OSS_LOGIN": "OSS Login",
            "SANDY_PROFILE": "Sandy Profile",
            "ACTIVE": "Active"
        },
        "predefined_values": {}
    },
    "Delivery Block Setup": {
        "table_name": "DELV_BLOCK_SETUP",
        "count_button": "Y",
        "select_button": "Y",
        "insert_button": "N",
        "update_button": "Y",
        "delete_button": "N",
        "user_locked": "N",
        "allowed_insert_grp": "",
        "allowed_update_grp": "",
        "allowed_delete_grp": "",
        "description": "",
        "wiki_link": "",
        "column_labels": {
            "SAPSYSTEM": "SAPSYSTEM",
            "DELIVERY_BLOCK": "DELIVERY_BLOCK",
            "DELIVERY_BLOCK_TEXT": "DELIVERY_BLOCK_TEXT",
            "BLOCK_CATEGORY": "Classification",
            "EXTERNAL_TEXT": "OrderStatus Text",
            "INTERNAL_TEXT": "SANDY Text",
            "RECORD_STATE": "RECORD_STATE"
        },
        "predefined_values": {
            "BLOCK_CATEGORY": {
                "hide": "Hide",
                "info": "Informational",
                "oe/cr": "Order Entry - Credit",
                "oe/cfg": "Order Entry - Configuration",
                "oe/doc": "Order Entry - Missing Doc",
                "oe/info": "Order Entry - Missing Info",
                "oe/pri": "Order Entry - Pricing",
                "oe/pro": "Order Entry - Product",
                "oe/stax": "Order Entry - Tax Hold, T&Cs",
                "oe/acc": "Order Entry - Account",
                "oe/bitf": "Order Entry - Bitfone Order",
                "oe/cont": "Order Entry - Contract",
                "oe/cust": "Order Entry - Customer",
                "oe/cins": "Order Entry - Customer Inspection Hold",
                "oe/cmov": "Order Entry - Customer MOV (Min Order Value)",
                "oe/crp": "Order Entry - Customer Road Permit",
                "oe/data": "Order Entry - Data Setup Error",
                "oe/deal": "Order Entry - Deal",
                "oe/dpri": "Order Entry - Deal Pricing",
                "oe/dupo": "Order Entry - Duplicate PO Hold",
                "oe/eord": "Order Entry - eOrder Auto Hold",
                "oe/fulcr": "Order Entry - Fulfillment Credit Hold",
                "oe/leas": "Order Entry - Leasing Issue",
                "oe/lic": "Order Entry - License / RPL Issue",
                "oe/man": "Order Entry - Manual Hold",
                "oe/ois": "Order Entry - OIS Fallout",
                "oe/oee": "Order Entry - Order Entry Error",
                "oe/pay": "Order Entry - Payment / Cash in Advance",
                "oe/res": "Order Entry - Reservation Order",
                "oe/so": "Order Entry - Sales Office Hold",
                "oe/serv": "Order Entry - Services",
                "oe/ship": "Order Entry - Ship Hold",
                "oe/shto": "Order Entry - Ship To Issue",
                "oe/skel": "Order Entry - Skeleton Order",
                "oe/supp": "Order Entry - Supplier Info Issue",
                "oe/vdps": "Order Entry - VDPS Order",
                "oe/oth": "Order Entry - Other",
                "ff/cfg": "Factory Fulfillment - Configuration",
                "ff/doc": "Factory Fulfillment - Missing Doc",
                "ff/mat": "Factory Fulfillment - Material",
                "ff/chg": "Factory Fulfillment - Change",
                "ff/uns": "Factory Fulfillment - Unschedule",
                "ff/cons": "Factory Fulfillment - Consolidated Delivery Hold",
                "ff/alli": "Factory Fulfillment - Alliance Hold",
                "ff/alloc": "Factory Fulfillment - Allocation Issue",
                "ff/cred": "Factory Fulfillment - Credit Reload",
                "ff/esc1": "Factory Fulfillment - Escalation / Expedite Lev. 1",
                "ff/esc2": "Factory Fulfillment - Escalation / Expedite Lev. 2",
                "ff/esc3": "Factory Fulfillment - Escalation / Expedite Lev. 3",
                "ff/fact": "Factory Fulfillment - Factory Hold",
                "ff/exp": "Factory Fulfillment - Export Hold",
                "ff/npi": "Factory Fulfillment - NPI",
                "ff/obs": "Factory Fulfillment - Obsolete Product",
                "ff/plant": "Factory Fulfillment - Plant Issue",
                "ff/prod": "Factory Fulfillment - Product Hold",
                "ff/shipm": "Factory Fulfillment - Shipment Hold",
                "ff/tba": "Factory Fulfillment - TBA",
                "ff/oth": "Factory Fulfillment - Other",
                "ship/tra": "Shipping - Traffic",
                "ship/mer": "Shipping - Merge",
                "ship/sch": "Shipping - Scheduled",
                "ship/fo": "Shipping - Fallout",
                "ship": "Shipping - Other",
                "bill/inv": "Billing - Invoice",
                "bill/part": "Billing - Partial Invoice",
                "bill": "Billing - Other",
                "fo/sap": "Fall Out - SAP",
                "st/awcf": "Status - Awaiting Config Check",
                "st/awcr": "Status - Awaiting Credit",
                "st/awrp": "Status - Awaiting Release to Production",
                "st/ffw": "Status - FF WIP",
                "st/oew": "Status - OE WIP",
                "st/shw": "Status - Ship WIP",
                "can": "Cancel"
            }
        }
    },
    "Eclaims Activity Setup ": {
        "table_name": "ECLAIM_ACTIVITY_SETUP",
        "count_button": "Y",
        "select_button": "Y",
        "insert_button": "N",
        "update_button": "Y",
        "delete_button": "Y",
        "user_locked": "N",
        "allowed_insert_grp": "",
        "allowed_update_grp": "",
        "allowed_delete_grp": "",
        "description": "",
        "wiki_link": "",
        "column_labels": {
            "ACTIVITY_ID": "Activity ID",
            "EXTERNAL_TEXT": "Text in SANDY",
            "USED_IN_SANDY": "Used in SANDY"
        },
        "predefined_values": {
            "USED_IN_SANDY": {
                "Y": "Yes",
                "N": "No"
            }
        }
    },
    "Reason Code Setup": {
        "table_name": "REASONCODE",
        "count_button": "Y",
        "select_button": "Y",
        "insert_button": "Y",
        "update_button": "Y",
        "delete_button": "Y",
        "user_locked": "N",
        "allowed_insert_grp": "",
        "allowed_update_grp": "",
        "allowed_delete_grp": "",
        "description": "",
        "wiki_link": "",
        "column_labels": {
            "REASONCODE": "Reason Code",
            "DESCRIPTION": "Description",
            "ISPLAYORDER": "Display Order"
        },
        "predifined_values": {}
    },
    "Sla Mapping Setup": {
        "table_name": "SLA_MAP",
        "count_button": "Y",
        "select_button": "Y",
        "insert_button": "Y",
        "update_button": "Y",
        "delete_button": "Y",
        "user_locked": "N",
        "allowed_insert_grp": "",
        "allowed_update_grp": "",
        "allowed_delete_grp": "",
        "description": "",
        "wiki_link": "",
        "column_labels": {
            "PROD_TYPE_NAME": "Product Type Name",
            "SLA_CATEGORY": "Sla Category",
            "PROD_CATEGORY": "Product Category",
            "PROD_SUBCATEGORY": "Product Subcategory",
            "PROD_TYPE_CODE": "Product Type Code"
        },
        "predifined_values": {}
    },
    "Status Code Setup": {
        "table_name": "STATUSCODE",
        "count_button": "Y",
        "select_button": "Y",
        "insert_button": "Y",
        "update_button": "Y",
        "delete_button": "Y",
        "user_locked": "N",
        "allowed_insert_grp": "",
        "allowed_update_grp": "",
        "allowed_delete_grp": "",
        "description": "",
        "wiki_link": "",
        "column_labels": {
            "STATUSCODE": "Status Code",
            "DESCRIPTION": "Description",
            "DISPLAYORDER": "Display Order",
            "EVENT_IN_FUTURE": "Event in future",
            "SCOUT_EVENT": "Scout Event",
            "SOURCESYSTEM": "Source System"
        },
        "predifined_values": {}
    },
    "UNSPSC Hierarchy Setup": {
        "table_name": "UNSPSC_HIERARCHY",
        "count_button": "Y",
        "select_button": "Y",
        "insert_button": "Y",
        "update_button": "Y",
        "delete_button": "Y",
        "user_locked": "N",
        "allowed_insert_grp": "",
        "allowed_update_grp": "",
        "allowed_delete_grp": "",
        "description": "",
        "wiki_link": "",
        "column_labels": {
            "SEGMENT": "Segment",
            "FAMILY": "Family",
            "CLASS": "Class",
            "UNSPSC": "Unspsc"
        },
        "predifined_values": {}
    },
    "User Status / Hold Categories / Cancelation Reason Setup": {
        "table_name": "USERSYS_STATUS_SETUP",
        "count_button": "Y",
        "select_button": "Y",
        "insert_button": "Y",
        "update_button": "Y",
        "delete_button": "Y",
        "user_locked": "N",
        "allowed_insert_grp": "",
        "allowed_update_grp": "",
        "allowed_delete_grp": "",
        "description": "",
        "wiki_link": "",
        "column_labels": {
            "STYPE": "StatusType",
            "EXTERNAL_TEXT": "",
            "USERSYS_STATUS": "User/SystemStatusCode",
            "USERSYS_STATUS_TEXT": "User/SystemStatusText",
            "INTERNAL_TEXT": "SANDYText",
            "BLOCK_CATEGORY": "Classification",
            "CREDIT_TEXT": "",
            "BLOCK_TEXT": "",
            "EXTERNAL_BLOCK_TEXT": "OrderStatusText",
            "MAT_STATUS_TEXT": "",
            "RECORD_STATE": "RecordState",
            "CANCELATION_REASON": "ReasonforCancelation",
            "SYSTEM_REJECTION": "SystemReject"
        },
        "predifined_values": {
            "CANCELATION_REASON": {
                "none": "n/a",
                "User_Iniated_Cancelation": "UserIniatedCancelation",
                "Fraud_Cancelation": "FraudCancelation",
                "Lease_Cancelation": "LeaseCancelation",
                "Credit_Card_Rejection": "CreditCardRejection",
                "Settlement_Failure_Frontend": "SettlementFailure(Frontend)",
                "Settlement_Failure_Backend": "SettlementFailure(Backend)",
                "Sales_Rep_Rejection": "SalesRepRejection",
                "VCP_Rejection": "VCPRejection",
                "GTS_Rejection": "GTSRejection",
                "System_Rejection": "SystemRejection"
            },
            "BLOCK_CATEGORY": {
                "hide": "Hide",
                "info": "Informational",
                "oe/cr": "OrderEntry-Credit",
                "oe/cfg": "OrderEntry-Configuration",
                "oe/doc": "OrderEntry-MissingDoc",
                "oe/info": "OrderEntry-MissingInfo",
                "oe/pri": "OrderEntry-Pricing",
                "oe/pro": "OrderEntry-Product",
                "oe/stax": "OrderEntry-TaxHoldT&Cs",
                "oe/acc": "OrderEntry-Account",
                "oe/bitf": "OrderEntry-BitfoneOrder",
                "oe/cont": "OrderEntry-Contract",
                "oe/cust": "OrderEntry-Customer",
                "oe/cins": "OrderEntry-CustomerInspectionHold",
                "oe/cmov": "OrderEntry-CustomerMOV(MinOrderValue)",
                "oe/crp": "OrderEntry-CustomerRoadPermit",
                "oe/data": "OrderEntry-DataSetupError",
                "oe/deal": "OrderEntry-Deal",
                "oe/dpri": "OrderEntry-DealPricing",
                "oe/dupo": "OrderEntry-DuplicatePOHold",
                "oe/eord": "OrderEntry-eOrderAutoHold",
                "oe/fulcr": "OrderEntry-FulfillmentCreditHold",
                "oe/leas": "OrderEntry-LeasingIssue",
                "oe/lic": "OrderEntry-License/RPLIssue",
                "oe/man": "OrderEntry-ManualHold",
                "oe/ois": "OrderEntry-OISFallout",
                "oe/oee": "OrderEntry-OrderEntryError",
                "oe/pay": "OrderEntry-Payment/CashinAdvance",
                "oe/res": "OrderEntry-ReservationOrder",
                "oe/so": "OrderEntry-SalesOfficeHold",
                "oe/serv": "OrderEntry-Services",
                "oe/ship": "OrderEntry-ShipHold",
                "oe/shto": "OrderEntry-ShipToIssue",
                "oe/skel": "OrderEntry-SkeletonOrder",
                "oe/supp": "OrderEntry-SupplierInfoIssue",
                "oe/vdps": "OrderEntry-VDPSOrder",
                "oe/oth": "OrderEntry-Other",
                "ff/cfg": "FactoryFulfillment-Configuration",
                "ff/doc": "FactoryFulfillment-MissingDoc",
                "ff/mat": "FactoryFulfillment-Material",
                "ff/chg": "FactoryFulfillment-Change",
                "ff/uns": "FactoryFulfillment-Unschedule",
                "ff/cons": "FactoryFulfillment-ConsolidatedDeliveryHold",
                "ff/alli": "FactoryFulfillment-AllianceHold",
                "ff/alloc": "FactoryFulfillment-AllocationIssue",
                "ff/cred": "FactoryFulfillment-CreditReload",
                "ff/esc1": "FactoryFulfillment-Escalation/ExpediteLev.1",
                "ff/esc2": "FactoryFulfillment-Escalation/ExpediteLev.2",
                "ff/esc3": "FactoryFulfillment-Escalation/ExpediteLev.3",
                "ff/fact": "FactoryFulfillment-FactoryHold",
                "ff/exp": "FactoryFulfillment-ExportHold",
                "ff/npi": "FactoryFulfillment-NPI",
                "ff/obs": "FactoryFulfillment-ObsoleteProduct",
                "ff/plant": "FactoryFulfillment-PlantIssue",
                "ff/prod": "FactoryFulfillment-ProductHold",
                "ff/shipm": "FactoryFulfillment-ShipmentHold",
                "ff/tba": "FactoryFulfillment-TBA",
                "ff/oth": "FactoryFulfillment-Other",
                "ship/tra": "Shipping-Traffic",
                "ship/mer": "Shipping-Merge",
                "ship/sch": "Shipping-Scheduled",
                "ship/fo": "Shipping-Fallout",
                "ship": "Shipping-Other",
                "bill/inv": "Billing-Invoice",
                "bill/part": "Billing-PartialInvoice",
                "bill": "Billing-Other",
                "fo/sap": "FallOut-SAP",
                "st/awcf": "Status-AwaitingConfigCheck",
                "st/awcr": "Status-AwaitingCredit",
                "st/awrp": "Status-AwaitingReleasetoProduction",
                "st/ffw": "Status-FFWIP",
                "st/oew": "Status-OEWIP",
                "st/shw": "Status-ShipWIP",
                "can": "Cancel"
            }
        }
    },
    "WebService Setup": {
        "table_name": "WEB_SERVICE",
        "count_button": "Y",
        "select_button": "Y",
        "insert_button": "Y",
        "update_button": "Y",
        "delete_button": "Y",
        "user_locked": "N",
        "allowed_insert_grp": "",
        "allowed_update_grp": "",
        "allowed_delete_grp": "",
        "description": "",
        "wiki_link": "",
        "column_labels": {
            "ID": "Id",
            "CONTACT_NAME": "ContactName",
            "CONTACT_MAIL": "ContactMail",
            "SERVICE_NAME": "ServiceName",
            "TIMING": "Timing",
            "FORMAT": "Format",
            "TRANSPORT_URL": "TransportUrl",
            "TRANSPORT_USER": "TransportUser",
            "TRANSPORT_PASS": "TransportPass",
            "FILE_PATTERN": "FilePattern",
            "LOGDIR": "Logdir",
            "WITH_PRICES": "Withprices",
            "METHOD": "Method",
            "FILTERS": "Filters",
            "EXPIRE_DATE": "Expiredate",
            "CREATION_DATE": "Creationdate",
            "MULTIPLE_ALLOWED": "Multipleallowed"
        },
        "predifined_values": {}
    },
    "Storefront Email Setup": {
        "table_name": "STOREFRONT_EMAIL_SETUP",
        "count_button": "Y",
        "select_button": "Y",
        "insert_button": "Y",
        "update_button": "Y",
        "delete_button": "Y",
        "user_locked": "N",
        "allowed_insert_grp": "",
        "allowed_update_grp": "",
        "allowed_delete_grp": "",
        "description": "",
        "wiki_link": "",
        "column_labels": {
            "SF_NAME": "StorefrontFullName",
            "TEMPLATE": "Storefront",
            "GEO": "StorefrontCountry",
            "LANGUAGE_DEFAULT": "DefaultLanguage",
            "LANGUAGE_SOURCE": "Thefieldforlanguage",
            "LANGUAGE_OVERWRITE": "Overwritethelanguage",
            "EMAIL_ADDRESSES": "Thefield(s)foremailaddress",
            "EMAIL_OVERWRITE": "Overwritetheemailaddress",
            "EMAIL_CC_TEST": "Emailaddressfortests",
            "ADMIN": "Theadminevent",
            "ACKED": "Theackedevent",
            "DELIVERED": "Thedeliveredevent",
            "SUBMITTED": "Thesubmittedevent",
            "SHIPPED": "Theshippedevent",
            "INVOICED": "Theinvoicedevent",
            "CANCELED": "Thecanceledevent",
            "CANCELED_ITEM": "Thecanceleditemevent",
            "ELFPACK": "Theelfpackevent",
            "ADD_EVENT": "Additionalevent",
            "LIVE_ENABLED": "Liveemail",
            "LIVE_TEMPLATE": "TheLiveemailtemplate"
        },
        "predifined_values": {
            "SF_NAME": {
                "ISCS_CH": "ISCS_CH",
                "ISCS_DE": "ISCS_DE",
                "ISCS_FR": "ISCS_FR",
                "ISCS_UK": "ISCS_UK",
                "ISCS_GB": "ISCS_GB",
                "ISCS_ES": "ISCS_ES",
                "ISCS_SE": "ISCS_SE",
                "EBAY_DE": "EBAY_DE"
            },
            "TEMPLATE": {
                "ISCS": "ISCS",
                "EBAY": "EBAY"
            },
            "GEO": {
                "DE": "DE",
                "CH": "CH",
                "FR": "FR",
                "UK": "UK",
                "ES": "ES",
                "SE": "SE"
            }
        }
    },
    "Delivery Comment Setup": {
        "table_name": "SHIPMENT_COMMENTS",
        "count_button": "Y",
        "select_button": "Y",
        "insert_button": "N",
        "update_button": "N",
        "delete_button": "N",
        "user_locked": "Y",
        "allowed_insert_grp": "cap:CommitRulesAdmin:insert",
        "allowed_update_grp": "cap:CommitRulesAdmin:update",
        "allowed_delete_grp": "cap:CommitRulesAdmin:delete",
        "description": "This table allows to set up by Region and route if and what communcation should be shared with the customer in case a shipment is overdue. The selected communication is displayed in the field Delivery Comment.",
        "wiki_link": "http://ossws-tst.corp.hp.com:8888/IndexScreens/ShipmentCommentsSetup",
        "column_labels": {
            "OM_REGION": "Region",
            "RTM": "Route To Market",
            "BT": "Business Type",
            "FIRSTPSDOVERDUE": "Fisrt PSD not available",
            "SHIPMENTOVERDUELESS5DAYS": "Shipment Overdue <= 5 Work Days",
            "SHIPMENTOVERDUEGREATER5DAYS": "Shipment Overdue > 5 Work Days",
            "DELIVERYOVERDUELESS5DAYS": "Delivery Overdue <= 5 Work Days",
            "DELIVERYOVERDUEGREATER5DAYS": "Delivery Overdue > 5 Work Days"
        },
        "predefined_values": {
            "OM_REGION": {
                "APJ": "APJ",
                "CA": "CA",
                "EMEA": "EMEA",
                "LA": "LA",
                "US": "US"
            },
            "RTM": {
                "D": "Direct",
                "I": "Indirect",
                "All": "All"
            },
            "BT": {
                "O": "Volume",
                "A": "Value",
                "K": "Kiosk",
                "All": "All"
            },
            "FIRSTPSDOVERDUE": {
                "To be advised": "To be advised"
            },
            "SHIPMENTOVERDUELESS5DAYS": {
                "Shipment Delay": "Shipment Delay"
            },
            "SHIPMENTOVERDUEGREATER5DAYS": {
                "Shipment Delay, please contact HP": "Shipment Delay, please contact HP"
            },
            "DELIVERYOVERDUELESS5DAYS": {
                "Y": "Use SSM",
                "N": "N"
            },
            "DELIVERYOVERDUEGREATER5DAYS": {
                "No POD was received please check with carrier": "No POD was received please check with carrier",
                "No POD was received please contact HP support": "No POD was received please contact HP support"
            }
        }
    },
    "Rejection Code Setup": {
        "table_name": "REJECTION_CODE_SETUP",
        "count_button": "Y",
        "select_button": "Y",
        "insert_button": "N",
        "update_button": "Y",
        "delete_button": "N",
        "user_locked": "N",
        "allowed_insert_grp": "",
        "allowed_update_grp": "",
        "allowed_delete_grp": "",
        "description": "",
        "wiki_link": "",
        "column_labels": {
            "REJECTION_CODE": "Rejection Code",
            "REJECTION_CODE_TEXT": "Rejection Code Text",
            "EXTERNAL_TEXT": "OrderStatus Text",
            "INTERNAL_TEXT": "SANDY Text",
            "BLOCK_CATEGORY": "Classification",
            "CREDIT_BLOCK_TEXT": "Credit Block Text",
            "BLOCK_TEXT": "Block Text",
            "CANCELLATION": "Cancellation"
        },
        "predefined_values": {
            "CANCELLATION": {
                "Y": "Y",
                "N": "N"
            },
            "BLOCK_CATEGORY": {
                "hide": "Hide",
                "info": "Informational",
                "oe/cr": "Order Entry - Credit",
                "oe/cfg": "Order Entry - Configuration",
                "oe/doc": "Order Entry - Missing Doc",
                "oe/info": "Order Entry - Missing Info",
                "oe/pri": "Order Entry - Pricing",
                "oe/pro": "Order Entry - Product",
                "oe/stax": "Order Entry - Tax Hold, T&Cs",
                "oe/acc": "Order Entry - Account",
                "oe/bitf": "Order Entry - Bitfone Order",
                "oe/cont": "Order Entry - Contract",
                "oe/cust": "Order Entry - Customer",
                "oe/cins": "Order Entry - Customer Inspection Hold",
                "oe/cmov": "Order Entry - Customer MOV (Min Order Value)",
                "oe/crp": "Order Entry - Customer Road Permit",
                "oe/data": "Order Entry - Data Setup Error",
                "oe/deal": "Order Entry - Deal",
                "oe/dpri": "Order Entry - Deal Pricing",
                "oe/dupo": "Order Entry - Duplicate PO Hold",
                "oe/eord": "Order Entry - eOrder Auto Hold",
                "oe/fulcr": "Order Entry - Fulfillment Credit Hold",
                "oe/leas": "Order Entry - Leasing Issue",
                "oe/lic": "Order Entry - License / RPL Issue",
                "oe/man": "Order Entry - Manual Hold",
                "oe/ois": "Order Entry - OIS Fallout",
                "oe/oee": "Order Entry - Order Entry Error",
                "oe/pay": "Order Entry - Payment / Cash in Advance",
                "oe/res": "Order Entry - Reservation Order",
                "oe/so": "Order Entry - Sales Office Hold",
                "oe/serv": "Order Entry - Services",
                "oe/ship": "Order Entry - Ship Hold",
                "oe/shto": "Order Entry - Ship To Issue",
                "oe/skel": "Order Entry - Skeleton Order",
                "oe/supp": "Order Entry - Supplier Info Issue",
                "oe/vdps": "Order Entry - VDPS Order",
                "oe/oth": "Order Entry - Other",
                "ff/cfg": "Factory Fulfillment - Configuration",
                "ff/doc": "Factory Fulfillment - Missing Doc",
                "ff/mat": "Factory Fulfillment - Material",
                "ff/chg": "Factory Fulfillment - Change",
                "ff/uns": "Factory Fulfillment - Unschedule",
                "ff/cons": "Factory Fulfillment - Consolidated Delivery Hold",
                "ff/alli": "Factory Fulfillment - Alliance Hold",
                "ff/alloc": "Factory Fulfillment - Allocation Issue",
                "ff/cred": "Factory Fulfillment - Credit Reload",
                "ff/esc1": "Factory Fulfillment - Escalation / Expedite Lev. 1",
                "ff/esc2": "Factory Fulfillment - Escalation / Expedite Lev. 2",
                "ff/esc3": "Factory Fulfillment - Escalation / Expedite Lev. 3",
                "ff/fact": "Factory Fulfillment - Factory Hold",
                "ff/exp": "Factory Fulfillment - Export Hold",
                "ff/npi": "Factory Fulfillment - NPI",
                "ff/obs": "Factory Fulfillment - Obsolete Product",
                "ff/plant": "Factory Fulfillment - Plant Issue",
                "ff/prod": "Factory Fulfillment - Product Hold",
                "ff/shipm": "Factory Fulfillment - Shipment Hold",
                "ff/tba": "Factory Fulfillment - TBA",
                "ff/oth": "Factory Fulfillment - Other",
                "ship/tra": "Shipping - Traffic",
                "ship/mer": "Shipping - Merge",
                "ship/sch": "Shipping - Scheduled",
                "ship/fo": "Shipping - Fallout",
                "ship": "Shipping - Ohter",
                "bill/inv": "Billing - Invoice",
                "bill/part": "Billing - Partial Invoice",
                "bill": "Billing - Other ",
                "fo/sap": "Fall Out - SAP",
                "st/awcf": "Status - Awaiting Config Check",
                "st/awcr": "Status - Awaiting Credit",
                "st/awrp": "Status - Awaiting Release to Production",
                "st/ffw": "Status - FF WIP",
                "st/oew": "Status - OE WIP",
                "st/shw": "Status - Ship WIP",
                "can": "Cancel"
            }
        }
    },
    "Reason Code Setup": {
        "table_name": "OP_CODE_SETUP",
        "count_button": "Y",
        "select_button": "Y",
        "insert_button": "Y",
        "update_button": "Y",
        "delete_button": "N",
        "user_locked": "N",
        "allowed_insert_grp": "",
        "allowed_update_grp": "",
        "allowed_delete_grp": "",
        "description": "",
        "wiki_link": "",
        "column_labels": {
            "SAPSYSTEM": "System",
            "REASONCODE": "Change Reason Code",
            "DESCRIPTION": "Description",
            "CUSTOMER_INITIATED": "Customer initated Cancelation",
            "EXTERNAL_TEXT": "External Text",
            "INTERNAL_TEXT": "Internal Text"
        },
        "predefined_values": {
            "CUSTOMER_INITIATED": {
                "Y": "yes",
                "N": "no"
            }
        }
    },
    "Order Origin Code Setup": {
        "table_name": "ORDER_ORIGIN_SETUP",
        "count_button": "Y",
        "select_button": "Y",
        "insert_button": "N",
        "update_button": "Y",
        "delete_button": "N",
        "user_locked": "N",
        "allowed_insert_grp": "",
        "allowed_update_grp": "",
        "allowed_delete_grp": "",
        "description": "",
        "wiki_link": "",
        "column_labels": {
            "SAPSYSTEM": "System",
            "CODE": "Code",
            "TYPE": "Type",
            "DESCRIPTION": "Code Text",
            "INTERNAL_TEXT": "SANDY Text",
            "SUBMISSION_METHOD": "Submission Method"
        },
        "predefined_values": {}
    }
}
