$axure.loadCurrentPage({
  "url":"index.html",
  "generationDate":new Date(1425961337781.64),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a749395f36d440b6a19797b5bcd52729",
    "type":"Axure:Page",
    "name":"Index",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
      "a":{
},
      "b":{
}},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e78397bf7a50407088e8c013b45e1d98",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
            "a":{
},
            "b":{
}},
          "masterId":"b5c24b157dba4ee59e348e23b32237b5"}]}},
  "masters":{
    "b5c24b157dba4ee59e348e23b32237b5":{
      "packageId":"b5c24b157dba4ee59e348e23b32237b5",
      "type":"Axure:Master",
      "name":"Footer",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
        "a":{
},
        "b":{
}},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"1f4ab075a1454e79af3f058c4ea204ae",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":-42,
                "y":868},
              "size":{
                "width":1024,
                "height":50}},
            "adaptiveStyles":{
              "a":{
},
              "b":{
}},
            "objects":[{
                "id":"81aa2da56ab3468b86589da99a32d564",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":-42,
                    "y":868},
                  "size":{
                    "width":1024,
                    "height":50}},
                "adaptiveStyles":{
                  "a":{
},
                  "b":{
}}}],
            "images":{
              "normal~":"images/index/u1.png"}},
{
            "id":"69d4787dfef74445a490e87e1d5e3ee2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"12px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF343434,
                "opacity":1},
              "location":{
                "x":686,
                "y":881},
              "size":{
                "width":154,
                "height":14}},
            "adaptiveStyles":{
              "a":{
},
              "b":{
}},
            "objects":[{
                "id":"621b11a230c84ee5b6b3b22bfa30d1a0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"12px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF343434,
                    "opacity":1},
                  "location":{
                    "x":686,
                    "y":881},
                  "size":{
                    "width":154,
                    "height":14}},
                "adaptiveStyles":{
                  "a":{
},
                  "b":{
}}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"1f1f32c1f45f49e4b073469af5a98382",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"12px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF343434,
                "opacity":1},
              "location":{
                "x":867,
                "y":881},
              "size":{
                "width":72,
                "height":14}},
            "adaptiveStyles":{
              "a":{
},
              "b":{
}},
            "objects":[{
                "id":"640bbf84b6ec4f278885caa0f7bbfdd5",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"12px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF343434,
                    "opacity":1},
                  "location":{
                    "x":867,
                    "y":881},
                  "size":{
                    "width":72,
                    "height":14}},
                "adaptiveStyles":{
                  "a":{
},
                  "b":{
}}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ff4d5e2d8b8b4c428edc032f79d22348",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"12px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF343434,
                "opacity":1},
              "location":{
                "x":75,
                "y":881},
              "size":{
                "width":251,
                "height":14}},
            "adaptiveStyles":{
              "a":{
},
              "b":{
}},
            "objects":[{
                "id":"c1a8e7b6cc87400e84560b52a4d1ec49",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"12px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF343434,
                    "opacity":1},
                  "location":{
                    "x":75,
                    "y":881},
                  "size":{
                    "width":251,
                    "height":14}},
                "adaptiveStyles":{
                  "a":{
},
                  "b":{
}}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Link in Current Window",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"5e379e598c1c480b92b6d224a931a294",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"12px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF343434,
                "opacity":1},
              "location":{
                "x":46,
                "y":598},
              "size":{
                "width":327,
                "height":14},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
},
              "b":{
}},
            "objects":[{
                "id":"7c049c2fae3d41b7a55ac8a8d12d8c7e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"12px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF343434,
                    "opacity":1},
                  "location":{
                    "x":46,
                    "y":598},
                  "size":{
                    "width":327,
                    "height":14},
                  "limbo":true},
                "adaptiveStyles":{
                  "a":{
},
                  "b":{
}}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"60547190c9374e4fbb3480537b554429",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":678},
              "size":{
                "width":50,
                "height":50},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
},
              "b":{
}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Link in Current Window",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"b21302b62e604233aa8430a5521fb15c",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":688},
              "size":{
                "width":50,
                "height":50},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
},
              "b":{
}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Link in Current Window",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"1ae62c75ccae4a14a5fb1d23bfb5b6c8",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":60,
                "y":688},
              "size":{
                "width":50,
                "height":50},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
},
              "b":{
}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Link in Current Window",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"5a7b38a5c1e24c3e95402c2536f618cb",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":140,
                "y":678},
              "size":{
                "width":50,
                "height":50},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
},
              "b":{
}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Link in Current Window",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"7118088c56064fddbddc6b751378f9ec",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":210,
                "y":678},
              "size":{
                "width":50,
                "height":50},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
},
              "b":{
}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Link in Current Window",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"a8eb0dae846045f5bd9cccc7e334f932",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":271,
                "y":678},
              "size":{
                "width":50,
                "height":50},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
},
              "b":{
}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Link in Current Window",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}}},
  "objectPaths":{
    "e78397bf7a50407088e8c013b45e1d98":{
      "scriptId":"u0",
      "1f4ab075a1454e79af3f058c4ea204ae":{
        "scriptId":"u1"},
      "81aa2da56ab3468b86589da99a32d564":{
        "scriptId":"u2"},
      "69d4787dfef74445a490e87e1d5e3ee2":{
        "scriptId":"u3"},
      "621b11a230c84ee5b6b3b22bfa30d1a0":{
        "scriptId":"u4"},
      "1f1f32c1f45f49e4b073469af5a98382":{
        "scriptId":"u5"},
      "640bbf84b6ec4f278885caa0f7bbfdd5":{
        "scriptId":"u6"},
      "ff4d5e2d8b8b4c428edc032f79d22348":{
        "scriptId":"u7"},
      "c1a8e7b6cc87400e84560b52a4d1ec49":{
        "scriptId":"u8"},
      "5e379e598c1c480b92b6d224a931a294":{
        "scriptId":"u9"},
      "7c049c2fae3d41b7a55ac8a8d12d8c7e":{
        "scriptId":"u10"},
      "60547190c9374e4fbb3480537b554429":{
        "scriptId":"u11"},
      "b21302b62e604233aa8430a5521fb15c":{
        "scriptId":"u12"},
      "1ae62c75ccae4a14a5fb1d23bfb5b6c8":{
        "scriptId":"u13"},
      "5a7b38a5c1e24c3e95402c2536f618cb":{
        "scriptId":"u14"},
      "7118088c56064fddbddc6b751378f9ec":{
        "scriptId":"u15"},
      "a8eb0dae846045f5bd9cccc7e334f932":{
        "scriptId":"u16"}}}});