$axure.loadCurrentPage({
  "url":"dummy.html",
  "generationDate":new Date(1423041282005.48),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e1ca47374711410ba4b811308fba042c",
    "type":"Axure:Page",
    "name":"Dummy",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
      "a":{
},
      "b":{
}},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"320ab51276fa4a9cbdafb23ac98adf17",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":983,
              "height":581},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "size":{
                "width":750,
                "height":581},
              "limbo":false}},
          "objects":[{
              "id":"edb81589c0e645d3bbeeef430833fd4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":983,
                  "height":581},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"images/package_details/u1307.png",
            "normal~b":"images/package_details/u1307_b.png"}},
{
          "id":"2b1c340edb43496982239c6a616e0d42",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":983,
              "height":541},
            "limbo":true,
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "size":{
                "width":750,
                "height":541},
              "limbo":false}},
          "objects":[{
              "id":"81bb664c0f154322824f9283123be2d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":983,
                  "height":541},
                "limbo":true,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"images/package_details/u904.png",
            "normal~b":"images/package_details/u1309_b.png"}},
{
          "id":"6a25f0321e294aa09b8b23321b1ecbdf",
          "label":"Ite",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":982,
              "height":194},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "size":{
                "width":750,
                "height":340},
              "limbo":false}},
          "objects":[{
              "id":"c2edb21b2af5473792c60521196e071c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":982,
                  "height":194},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"images/package_details/ite_u906.png",
            "normal~b":"images/package_details/ite_u793_b.png"}},
{
          "id":"e1730a4669b145a094709a0a07d6dab9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":10,
              "y":310},
            "size":{
              "width":982,
              "height":30},
            "limbo":true,
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "size":{
                "width":750,
                "height":39},
              "limbo":false}},
          "objects":[{
              "id":"6b894a9eaa75408f85c5e50665718112",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":10,
                  "y":310},
                "size":{
                  "width":982,
                  "height":30},
                "limbo":true,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"images/package_details/u908.png",
            "normal~b":"images/package_details/u1313_b.png"}},
{
          "id":"18214faa83da404f9e8a9753af5808b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Bold', 'Helvetica'",
            "fontSize":"12px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":20,
              "y":318},
            "size":{
              "width":60,
              "height":25},
            "limbo":true,
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}},
          "objects":[{
              "id":"9c16d576906849719284f697a5f05a49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Bold', 'Helvetica'",
                "fontSize":"12px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":20,
                  "y":318},
                "size":{
                  "width":60,
                  "height":25},
                "limbo":true,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"images/package_details/u218.png",
            "normal~b":"images/package_details/u218.png"}},
{
          "id":"79b02035a44e441b8f6385a7ec4abe13",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"12px",
            "location":{
              "x":25,
              "y":87},
            "size":{
              "width":69,
              "height":14},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}},
          "objects":[{
              "id":"ac31c14991b940ea959d7d05bfe4af5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"12px",
                "location":{
                  "x":25,
                  "y":87},
                "size":{
                  "width":69,
                  "height":14},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif"}},
{
          "id":"bf94f7d8ce504388a17eb7a1ece8c50d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Bold', 'Helvetica'",
            "fontSize":"12px",
            "fontWeight":"700",
            "location":{
              "x":124,
              "y":87},
            "size":{
              "width":25,
              "height":14},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}},
          "objects":[{
              "id":"ee8bef8a18f242e2a39ab4c9b309be95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Bold', 'Helvetica'",
                "fontSize":"12px",
                "fontWeight":"700",
                "location":{
                  "x":124,
                  "y":87},
                "size":{
                  "width":25,
                  "height":14},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif"}},
{
          "id":"a698bd5ba3184c24bdffc88bdbf41e34",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"12px",
            "location":{
              "x":25,
              "y":135},
            "size":{
              "width":57,
              "height":14},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}},
          "objects":[{
              "id":"0c80f0231c8946b6ae540d8cccf539b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"12px",
                "location":{
                  "x":25,
                  "y":135},
                "size":{
                  "width":57,
                  "height":14},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif"}},
{
          "id":"b43a82d4bc12450aba7e44ec2e7faaa4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Bold', 'Helvetica'",
            "fontSize":"12px",
            "fontWeight":"700",
            "location":{
              "x":124,
              "y":135},
            "size":{
              "width":69,
              "height":14},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}},
          "objects":[{
              "id":"d801a186a19e49e0bc55791008b62fda",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Bold', 'Helvetica'",
                "fontSize":"12px",
                "fontWeight":"700",
                "location":{
                  "x":124,
                  "y":135},
                "size":{
                  "width":69,
                  "height":14},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif"}},
{
          "id":"e0b6d55b2f71459c847a7f8fe9958b33",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"12px",
            "location":{
              "x":279,
              "y":135},
            "size":{
              "width":46,
              "height":14},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}},
          "objects":[{
              "id":"2a9fcbed2cbf4d02944bfa883b7d226c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"12px",
                "location":{
                  "x":279,
                  "y":135},
                "size":{
                  "width":46,
                  "height":14},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif"}},
{
          "id":"bc0fc65a8ed844eeadcfdde626ca034d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":391,
              "y":131},
            "size":{
              "width":53,
              "height":25},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}}},
{
          "id":"5b25707712654ad4949b1ed463882346",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Bold', 'Helvetica'",
            "fontSize":"12px",
            "fontWeight":"700",
            "location":{
              "x":390,
              "y":239},
            "size":{
              "width":168,
              "height":81},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "size":{
                "width":120,
                "height":54},
              "limbo":false}},
          "objects":[{
              "id":"9c25d0e425874d8ca1d1dd63f99dca14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Bold', 'Helvetica'",
                "fontSize":"12px",
                "fontWeight":"700",
                "location":{
                  "x":390,
                  "y":239},
                "size":{
                  "width":168,
                  "height":81},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif"}},
{
          "id":"d53aa05123834bb6bb1a936092ad8daf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"12px",
            "location":{
              "x":540,
              "y":87},
            "size":{
              "width":47,
              "height":14},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}},
          "objects":[{
              "id":"d83c27bd549d456b8ed2e2fd4f0b47d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"12px",
                "location":{
                  "x":540,
                  "y":87},
                "size":{
                  "width":47,
                  "height":14},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif"}},
{
          "id":"69d1dd8bc909440bba6ae22cfef1c6b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"12px",
            "location":{
              "x":541,
              "y":195},
            "size":{
              "width":83,
              "height":14},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}},
          "objects":[{
              "id":"4cfb3b8605a0405798a8a1255797d637",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"12px",
                "location":{
                  "x":541,
                  "y":195},
                "size":{
                  "width":83,
                  "height":14},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif"}},
{
          "id":"4599229d0b6740c2b8ace9c5257639b0",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":645,
              "y":189},
            "size":{
              "width":88,
              "height":25},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}}},
{
          "id":"94e302aeea6b40f9a41471adaa6529fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"12px",
            "location":{
              "x":279,
              "y":87},
            "size":{
              "width":74,
              "height":14},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}},
          "objects":[{
              "id":"cfc7e139dd5943eda28585b05c987ea5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"12px",
                "location":{
                  "x":279,
                  "y":87},
                "size":{
                  "width":74,
                  "height":14},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif"}},
{
          "id":"c0cf6003774d4543906c4c6441488de4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Bold', 'Helvetica'",
            "fontSize":"12px",
            "fontWeight":"700",
            "location":{
              "x":391,
              "y":87},
            "size":{
              "width":23,
              "height":14},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}},
          "objects":[{
              "id":"b33fea10aecf413f8f896b8a4f4016fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Bold', 'Helvetica'",
                "fontSize":"12px",
                "fontWeight":"700",
                "location":{
                  "x":391,
                  "y":87},
                "size":{
                  "width":23,
                  "height":14},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif"}},
{
          "id":"cdd761951170421883cb2b9b46e4e5db",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"12px",
            "location":{
              "x":25,
              "y":239},
            "size":{
              "width":77,
              "height":14},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}},
          "objects":[{
              "id":"d9276249e3bc433caa06abac0c6ae214",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"12px",
                "location":{
                  "x":25,
                  "y":239},
                "size":{
                  "width":77,
                  "height":14},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif"}},
{
          "id":"71f067a325424ee2a0f60858911d7eec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Bold', 'Helvetica'",
            "fontSize":"12px",
            "fontWeight":"700",
            "location":{
              "x":124,
              "y":239},
            "size":{
              "width":80,
              "height":14},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}},
          "objects":[{
              "id":"5cbdbc70d6b147f188b8585fe028b90e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Bold', 'Helvetica'",
                "fontSize":"12px",
                "fontWeight":"700",
                "location":{
                  "x":124,
                  "y":239},
                "size":{
                  "width":80,
                  "height":14},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif"}},
{
          "id":"e2423bb77f8c45fe987f1e72b76e0451",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"12px",
            "location":{
              "x":279,
              "y":195},
            "size":{
              "width":83,
              "height":14},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}},
          "objects":[{
              "id":"c61b0070cacb4e81941172e25942e34c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"12px",
                "location":{
                  "x":279,
                  "y":195},
                "size":{
                  "width":83,
                  "height":14},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif"}},
{
          "id":"484551d0ecc947788e6c609122c91c22",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":189},
            "size":{
              "width":90,
              "height":25},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}}},
{
          "id":"201538a7a31f4bc8a25b1fa863adf990",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"12px",
            "location":{
              "x":279,
              "y":239},
            "size":{
              "width":62,
              "height":14},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}},
          "objects":[{
              "id":"c9771bf491ce4c3eab41a28ba8a456b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"12px",
                "location":{
                  "x":279,
                  "y":239},
                "size":{
                  "width":62,
                  "height":14},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif"}},
{
          "id":"1f8fb9c787a84ab78bd4addf69948f9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"12px",
            "location":{
              "x":541,
              "y":135},
            "size":{
              "width":55,
              "height":14},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}},
          "objects":[{
              "id":"a2c57acba7404ad5aef375c234872ad4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"12px",
                "location":{
                  "x":541,
                  "y":135},
                "size":{
                  "width":55,
                  "height":14},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif"}},
{
          "id":"2aab1c290e264e07b449dc37294ea127",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":643,
              "y":131},
            "size":{
              "width":88,
              "height":25},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}}},
{
          "id":"3ae520e4c232480083027cd08ad13dd9",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"12px",
            "location":{
              "x":643,
              "y":78},
            "size":{
              "width":88,
              "height":25},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}}},
{
          "id":"152b4dfe853345669a3773d162ff9ec7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"12px",
            "location":{
              "x":25,
              "y":195},
            "size":{
              "width":68,
              "height":14},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}},
          "objects":[{
              "id":"6d109fff0aa8425f9b0e7593abb731ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"12px",
                "location":{
                  "x":25,
                  "y":195},
                "size":{
                  "width":68,
                  "height":14},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif"}},
{
          "id":"912e1117f2424fafb1dc9a74630c9091",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Bold', 'Helvetica'",
            "fontSize":"12px",
            "fontWeight":"700",
            "location":{
              "x":124,
              "y":195},
            "size":{
              "width":66,
              "height":14},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}},
          "objects":[{
              "id":"8599f74055d0468da11f665496f80f8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Bold', 'Helvetica'",
                "fontSize":"12px",
                "fontWeight":"700",
                "location":{
                  "x":124,
                  "y":195},
                "size":{
                  "width":66,
                  "height":14},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif"}},
{
          "id":"fd7bbcfe4a7e4edc8eec852708dff7f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":348},
            "size":{
              "width":982,
              "height":41},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "size":{
                "width":750,
                "height":41},
              "limbo":false}},
          "objects":[{
              "id":"16c1841a19924e13a6e710e1e9765580",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":348},
                "size":{
                  "width":982,
                  "height":41},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"images/package_details/u133.png",
            "normal~b":"images/package_details/u133_b.png"}},
{
          "id":"6e354c7546384cbab7327e46c88a69ab",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":359},
            "size":{
              "width":20,
              "height":20},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}},
          "objects":[{
              "id":"dfeda52efe754929b6fb817c0a0c341a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":560,
                  "y":359},
                "size":{
                  "width":20,
                  "height":20},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set Panel to State",
                      "panelsToStates":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/shipping_details/u133.png",
            "normal~b":"images/shipping_details/u133.png"}},
{
          "id":"397526209e0441ac9c9c713416c423f1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":690,
              "y":359},
            "size":{
              "width":20,
              "height":20},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}},
          "objects":[{
              "id":"eacfc219a3f644aeb2130b2c15736f4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":690,
                  "y":359},
                "size":{
                  "width":20,
                  "height":20},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"images/package_details/u142.png",
            "normal~b":"images/package_details/u142.png"}},
{
          "id":"d352f4b7de6d4eaeb52e289468a9640e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":601,
              "y":359},
            "size":{
              "width":20,
              "height":20},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}},
          "objects":[{
              "id":"ce61cf48e2d3402faec23b47479532b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":601,
                  "y":359},
                "size":{
                  "width":20,
                  "height":20},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set Panel to State",
                      "panelsToStates":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/package_details/u144.png",
            "normal~b":"images/package_details/u144.png"}},
{
          "id":"5106243b20854c8489ed7a20eeab4d63",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":542,
              "y":348},
            "size":{
              "width":10,
              "height":41},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/shipping_details/u492_line.png",
            "start~a":"resources/images/transparent.gif",
            "end~a":"resources/images/transparent.gif",
            "line~a":"images/shipping_details/u492_line.png",
            "start~a":"resources/images/transparent.gif",
            "end~a":"resources/images/transparent.gif",
            "line~a":"images/shipping_details/u492_line.png",
            "start~b":"resources/images/transparent.gif",
            "end~b":"resources/images/transparent.gif",
            "line~b":"images/shipping_details/u492_line.png",
            "start~b":"resources/images/transparent.gif",
            "end~b":"resources/images/transparent.gif",
            "line~b":"images/shipping_details/u492_line.png"}},
{
          "id":"59a51724ab414b6bbde19148ba47eb58",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":584,
              "y":348},
            "size":{
              "width":10,
              "height":41},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/shipping_details/u492_line.png",
            "start~a":"resources/images/transparent.gif",
            "end~a":"resources/images/transparent.gif",
            "line~a":"images/shipping_details/u492_line.png",
            "start~a":"resources/images/transparent.gif",
            "end~a":"resources/images/transparent.gif",
            "line~a":"images/shipping_details/u492_line.png",
            "start~b":"resources/images/transparent.gif",
            "end~b":"resources/images/transparent.gif",
            "line~b":"images/shipping_details/u492_line.png",
            "start~b":"resources/images/transparent.gif",
            "end~b":"resources/images/transparent.gif",
            "line~b":"images/shipping_details/u492_line.png"}},
{
          "id":"f5b1c58aaf34490fa7609cb992eef8cf",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":674,
              "y":348},
            "size":{
              "width":10,
              "height":41},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/shipping_details/u492_line.png",
            "start~a":"resources/images/transparent.gif",
            "end~a":"resources/images/transparent.gif",
            "line~a":"images/shipping_details/u492_line.png",
            "start~a":"resources/images/transparent.gif",
            "end~a":"resources/images/transparent.gif",
            "line~a":"images/shipping_details/u492_line.png",
            "start~b":"resources/images/transparent.gif",
            "end~b":"resources/images/transparent.gif",
            "line~b":"images/shipping_details/u492_line.png",
            "start~b":"resources/images/transparent.gif",
            "end~b":"resources/images/transparent.gif",
            "line~b":"images/shipping_details/u492_line.png"}},
{
          "id":"4fe17da1ee5b4847b0c256cdbd767a96",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":10,
              "y":348},
            "size":{
              "width":40,
              "height":41},
            "limbo":true,
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}},
          "objects":[{
              "id":"a0e1c4ee165045329c365a1f343c8fe4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":10,
                  "y":348},
                "size":{
                  "width":40,
                  "height":41},
                "limbo":true,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"images/package_details/u149.png",
            "normal~b":"images/package_details/u149.png"}},
{
          "id":"c58a84fdfbaa4dafaa133dcc5123d803",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Bold', 'Helvetica Neue'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":25,
              "y":361},
            "size":{
              "width":8,
              "height":16},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}},
          "objects":[{
              "id":"33a08ae5e3ce4a04b548561aa3ce6546",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Bold', 'Helvetica Neue'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":25,
                  "y":361},
                "size":{
                  "width":8,
                  "height":16},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif"}},
{
          "id":"1c565a3ce2bc4deebe9f730f4285413a",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":715,
              "y":348},
            "size":{
              "width":10,
              "height":41},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/shipping_details/u492_line.png",
            "start~a":"resources/images/transparent.gif",
            "end~a":"resources/images/transparent.gif",
            "line~a":"images/shipping_details/u492_line.png",
            "start~a":"resources/images/transparent.gif",
            "end~a":"resources/images/transparent.gif",
            "line~a":"images/shipping_details/u492_line.png",
            "start~b":"resources/images/transparent.gif",
            "end~b":"resources/images/transparent.gif",
            "line~b":"images/shipping_details/u492_line.png",
            "start~b":"resources/images/transparent.gif",
            "end~b":"resources/images/transparent.gif",
            "line~b":"images/shipping_details/u492_line.png"}},
{
          "id":"b8da98bd5fa64e2b8ddb19c78df69ce1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":732,
              "y":359},
            "size":{
              "width":14,
              "height":20},
            "limbo":true,
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}},
          "objects":[{
              "id":"559da7c242e14e4b89728b0b31b17500",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":732,
                  "y":359},
                "size":{
                  "width":14,
                  "height":20},
                "limbo":true,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set Panel to State",
                      "panelsToStates":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/shipping_details/u135.png",
            "normal~b":"images/shipping_details/u135.png"}},
{
          "id":"d194c3685e23442b93f32f2bf887209d",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":629,
              "y":348},
            "size":{
              "width":10,
              "height":41},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/shipping_details/u492_line.png",
            "start~a":"resources/images/transparent.gif",
            "end~a":"resources/images/transparent.gif",
            "line~a":"images/shipping_details/u492_line.png",
            "start~a":"resources/images/transparent.gif",
            "end~a":"resources/images/transparent.gif",
            "line~a":"images/shipping_details/u492_line.png",
            "start~b":"resources/images/transparent.gif",
            "end~b":"resources/images/transparent.gif",
            "line~b":"images/shipping_details/u492_line.png",
            "start~b":"resources/images/transparent.gif",
            "end~b":"resources/images/transparent.gif",
            "line~b":"images/shipping_details/u492_line.png"}},
{
          "id":"d34f2642d6984868b18dbc1b86a748b1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":647,
              "y":359},
            "size":{
              "width":20,
              "height":20},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}},
          "objects":[{
              "id":"4b9541a897514a20832c78cdc14f0fef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":647,
                  "y":359},
                "size":{
                  "width":20,
                  "height":20},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set Panel to State",
                      "panelsToStates":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/package_details/u157.png",
            "normal~b":"images/package_details/u157.png"}},
{
          "id":"78b18bd9192742a98dccb2fd1621f20e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Regular', 'Helvetica'",
            "location":{
              "x":79,
              "y":361},
            "size":{
              "width":25,
              "height":16},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}},
          "objects":[{
              "id":"7df8a3c71fb145968f370aaeba480fa2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Regular', 'Helvetica'",
                "location":{
                  "x":79,
                  "y":361},
                "size":{
                  "width":25,
                  "height":16},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif"}},
{
          "id":"4f6d3172597f4330b729b7815607b582",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Regular', 'Helvetica'",
            "location":{
              "x":194,
              "y":360},
            "size":{
              "width":21,
              "height":16},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}},
          "objects":[{
              "id":"2ee20dbaa0e244afa60a7618ea6ad520",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Regular', 'Helvetica'",
                "location":{
                  "x":194,
                  "y":360},
                "size":{
                  "width":21,
                  "height":16},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif"}},
{
          "id":"d2d42e468a734862ad81986a9b9d1e05",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Regular', 'Helvetica'",
            "location":{
              "x":397,
              "y":360},
            "size":{
              "width":71,
              "height":16},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}},
          "objects":[{
              "id":"7f1a642b37f3468fb43b1db6f62564f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Regular', 'Helvetica'",
                "location":{
                  "x":397,
                  "y":360},
                "size":{
                  "width":71,
                  "height":16},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif"}},
{
          "id":"e135169d148b493bb69104ad7c6c9d5d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Regular', 'Helvetica'",
            "location":{
              "x":296,
              "y":361},
            "size":{
              "width":31,
              "height":16},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}},
          "objects":[{
              "id":"59a3decf774c435ea0ef352ac02c66ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Regular', 'Helvetica'",
                "location":{
                  "x":296,
                  "y":361},
                "size":{
                  "width":31,
                  "height":16},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif"}},
{
          "id":"695339a847304046927167ceb025e6a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":982,
              "height":41},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "size":{
                "width":750,
                "height":41},
              "limbo":false}},
          "objects":[{
              "id":"99fca92e3af04ebc95785fdf93d50820",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":982,
                  "height":41},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"images/package_details/u133.png",
            "normal~b":"images/package_details/u133_b.png"}},
{
          "id":"7254bb20ae7d4b0ab92c023ae0cacf68",
          "label":"Item type",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Regular', 'Helvetica'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":390,
              "y":18},
            "size":{
              "width":120,
              "height":25},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}},
          "interactionMap":{
            "onTextChange":{
              "description":"OnTextChange",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set Panel to State",
                      "panelsToStates":[]}]}]}}},
{
          "id":"7bfee84aba4d44d7ac104e51ff295d37",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"12px",
            "location":{
              "x":180,
              "y":18},
            "size":{
              "width":100,
              "height":25},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}}},
{
          "id":"f9336df9fc6643be93a54167ab5845d6",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"11px",
            "location":{
              "x":65,
              "y":18},
            "size":{
              "width":105,
              "height":25},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}}},
{
          "id":"17f2169a968b4b5fa0fbfb05edaeb617",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":542,
              "y":10},
            "size":{
              "width":10,
              "height":41},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/shipping_details/u492_line.png",
            "start~a":"resources/images/transparent.gif",
            "end~a":"resources/images/transparent.gif",
            "line~a":"images/shipping_details/u492_line.png",
            "start~a":"resources/images/transparent.gif",
            "end~a":"resources/images/transparent.gif",
            "line~a":"images/shipping_details/u492_line.png",
            "start~b":"resources/images/transparent.gif",
            "end~b":"resources/images/transparent.gif",
            "line~b":"images/shipping_details/u492_line.png",
            "start~b":"resources/images/transparent.gif",
            "end~b":"resources/images/transparent.gif",
            "line~b":"images/shipping_details/u492_line.png"}},
{
          "id":"59d8dee67a9c429ea56999231fe6b623",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":584,
              "y":10},
            "size":{
              "width":10,
              "height":41},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/shipping_details/u492_line.png",
            "start~a":"resources/images/transparent.gif",
            "end~a":"resources/images/transparent.gif",
            "line~a":"images/shipping_details/u492_line.png",
            "start~a":"resources/images/transparent.gif",
            "end~a":"resources/images/transparent.gif",
            "line~a":"images/shipping_details/u492_line.png",
            "start~b":"resources/images/transparent.gif",
            "end~b":"resources/images/transparent.gif",
            "line~b":"images/shipping_details/u492_line.png",
            "start~b":"resources/images/transparent.gif",
            "end~b":"resources/images/transparent.gif",
            "line~b":"images/shipping_details/u492_line.png"}},
{
          "id":"3643fae220ed47cea860f9188d795c3f",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":674,
              "y":10},
            "size":{
              "width":10,
              "height":41},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/shipping_details/u492_line.png",
            "start~a":"resources/images/transparent.gif",
            "end~a":"resources/images/transparent.gif",
            "line~a":"images/shipping_details/u492_line.png",
            "start~a":"resources/images/transparent.gif",
            "end~a":"resources/images/transparent.gif",
            "line~a":"images/shipping_details/u492_line.png",
            "start~b":"resources/images/transparent.gif",
            "end~b":"resources/images/transparent.gif",
            "line~b":"images/shipping_details/u492_line.png",
            "start~b":"resources/images/transparent.gif",
            "end~b":"resources/images/transparent.gif",
            "line~b":"images/shipping_details/u492_line.png"}},
{
          "id":"2e048ed0e45545f3967351e772c50cc5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":40,
              "height":41},
            "limbo":true,
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}},
          "objects":[{
              "id":"3c2f83b7a93d4f64b7d4131fc33f7b1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":40,
                  "height":41},
                "limbo":true,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"images/package_details/u149.png",
            "normal~b":"images/package_details/u149.png"}},
{
          "id":"d8aec3ea656e40c6b1490bd22c473490",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":715,
              "y":10},
            "size":{
              "width":10,
              "height":41},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/shipping_details/u492_line.png",
            "start~a":"resources/images/transparent.gif",
            "end~a":"resources/images/transparent.gif",
            "line~a":"images/shipping_details/u492_line.png",
            "start~a":"resources/images/transparent.gif",
            "end~a":"resources/images/transparent.gif",
            "line~a":"images/shipping_details/u492_line.png",
            "start~b":"resources/images/transparent.gif",
            "end~b":"resources/images/transparent.gif",
            "line~b":"images/shipping_details/u492_line.png",
            "start~b":"resources/images/transparent.gif",
            "end~b":"resources/images/transparent.gif",
            "line~b":"images/shipping_details/u492_line.png"}},
{
          "id":"95f2c17a928244b58ac531b2e3d5cbeb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":732,
              "y":21},
            "size":{
              "width":18,
              "height":18},
            "limbo":true,
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}},
          "objects":[{
              "id":"28e8945c22914cf189cafd1cdf3432a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":732,
                  "y":21},
                "size":{
                  "width":18,
                  "height":18},
                "limbo":true,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set Panel to State",
                      "panelsToStates":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/package_details/u857.png",
            "normal~b":"images/package_details/u857.png"}},
{
          "id":"fbe7cb27631c41eb9589811b0ed26525",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":629,
              "y":10},
            "size":{
              "width":10,
              "height":41},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/shipping_details/u492_line.png",
            "start~a":"resources/images/transparent.gif",
            "end~a":"resources/images/transparent.gif",
            "line~a":"images/shipping_details/u492_line.png",
            "start~a":"resources/images/transparent.gif",
            "end~a":"resources/images/transparent.gif",
            "line~a":"images/shipping_details/u492_line.png",
            "start~b":"resources/images/transparent.gif",
            "end~b":"resources/images/transparent.gif",
            "line~b":"images/shipping_details/u492_line.png",
            "start~b":"resources/images/transparent.gif",
            "end~b":"resources/images/transparent.gif",
            "line~b":"images/shipping_details/u492_line.png"}},
{
          "id":"59efdf698a4f4482982d6a0e8c013fde",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"12px",
            "location":{
              "x":290,
              "y":18},
            "size":{
              "width":90,
              "height":25},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}}},
{
          "id":"4336a1e247584cf68645fe6bd7067a27",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Bold', 'Helvetica Neue'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":25,
              "y":23},
            "size":{
              "width":8,
              "height":16},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}},
          "objects":[{
              "id":"3a83d0dc3e72433dbef90c477e00f00a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Bold', 'Helvetica Neue'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":25,
                  "y":23},
                "size":{
                  "width":8,
                  "height":16},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~b":"resources/images/transparent.gif"}},
{
          "id":"8ee2948f5ed9441cbfe1e6b766444b85",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":21},
            "size":{
              "width":20,
              "height":20},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}},
          "objects":[{
              "id":"8a6975cb8f954a09820bef9412754f97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":560,
                  "y":21},
                "size":{
                  "width":20,
                  "height":20},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set Panel to State",
                      "panelsToStates":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/shipping_details/u133.png",
            "normal~b":"images/shipping_details/u133.png"}},
{
          "id":"1e244d92eba74faaa805ffc64f119445",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":690,
              "y":21},
            "size":{
              "width":20,
              "height":20},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}},
          "objects":[{
              "id":"ec542f1472674abca180a44e13dacbc3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":690,
                  "y":21},
                "size":{
                  "width":20,
                  "height":20},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "images":{
            "normal~":"images/package_details/u142.png",
            "normal~b":"images/package_details/u142.png"}},
{
          "id":"68221993ba9540a38354a185307ed9df",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":601,
              "y":21},
            "size":{
              "width":20,
              "height":20},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}},
          "objects":[{
              "id":"6c7c75bdade242278859831c6087cd27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":601,
                  "y":21},
                "size":{
                  "width":20,
                  "height":20},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set Panel to State",
                      "panelsToStates":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/package_details/u144.png",
            "normal~b":"images/package_details/u144.png"}},
{
          "id":"8b97e429a6a14924a84734359b9d9282",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":647,
              "y":21},
            "size":{
              "width":20,
              "height":20},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
},
            "b":{
              "limbo":false}},
          "objects":[{
              "id":"b60cbfbf6e924629a1b95219e6bcf07a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":647,
                  "y":21},
                "size":{
                  "width":20,
                  "height":20},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
},
                "b":{
}}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set Panel to State",
                      "panelsToStates":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/package_details/u157.png",
            "normal~b":"images/package_details/u157.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "320ab51276fa4a9cbdafb23ac98adf17":{
      "scriptId":"u0"},
    "edb81589c0e645d3bbeeef430833fd4f":{
      "scriptId":"u1"},
    "2b1c340edb43496982239c6a616e0d42":{
      "scriptId":"u2"},
    "81bb664c0f154322824f9283123be2d7":{
      "scriptId":"u3"},
    "6a25f0321e294aa09b8b23321b1ecbdf":{
      "scriptId":"u4"},
    "c2edb21b2af5473792c60521196e071c":{
      "scriptId":"u5"},
    "e1730a4669b145a094709a0a07d6dab9":{
      "scriptId":"u6"},
    "6b894a9eaa75408f85c5e50665718112":{
      "scriptId":"u7"},
    "18214faa83da404f9e8a9753af5808b0":{
      "scriptId":"u8"},
    "9c16d576906849719284f697a5f05a49":{
      "scriptId":"u9"},
    "79b02035a44e441b8f6385a7ec4abe13":{
      "scriptId":"u10"},
    "ac31c14991b940ea959d7d05bfe4af5f":{
      "scriptId":"u11"},
    "bf94f7d8ce504388a17eb7a1ece8c50d":{
      "scriptId":"u12"},
    "ee8bef8a18f242e2a39ab4c9b309be95":{
      "scriptId":"u13"},
    "a698bd5ba3184c24bdffc88bdbf41e34":{
      "scriptId":"u14"},
    "0c80f0231c8946b6ae540d8cccf539b9":{
      "scriptId":"u15"},
    "b43a82d4bc12450aba7e44ec2e7faaa4":{
      "scriptId":"u16"},
    "d801a186a19e49e0bc55791008b62fda":{
      "scriptId":"u17"},
    "e0b6d55b2f71459c847a7f8fe9958b33":{
      "scriptId":"u18"},
    "2a9fcbed2cbf4d02944bfa883b7d226c":{
      "scriptId":"u19"},
    "bc0fc65a8ed844eeadcfdde626ca034d":{
      "scriptId":"u20"},
    "5b25707712654ad4949b1ed463882346":{
      "scriptId":"u21"},
    "9c25d0e425874d8ca1d1dd63f99dca14":{
      "scriptId":"u22"},
    "d53aa05123834bb6bb1a936092ad8daf":{
      "scriptId":"u23"},
    "d83c27bd549d456b8ed2e2fd4f0b47d9":{
      "scriptId":"u24"},
    "69d1dd8bc909440bba6ae22cfef1c6b1":{
      "scriptId":"u25"},
    "4cfb3b8605a0405798a8a1255797d637":{
      "scriptId":"u26"},
    "4599229d0b6740c2b8ace9c5257639b0":{
      "scriptId":"u27"},
    "94e302aeea6b40f9a41471adaa6529fa":{
      "scriptId":"u28"},
    "cfc7e139dd5943eda28585b05c987ea5":{
      "scriptId":"u29"},
    "c0cf6003774d4543906c4c6441488de4":{
      "scriptId":"u30"},
    "b33fea10aecf413f8f896b8a4f4016fd":{
      "scriptId":"u31"},
    "cdd761951170421883cb2b9b46e4e5db":{
      "scriptId":"u32"},
    "d9276249e3bc433caa06abac0c6ae214":{
      "scriptId":"u33"},
    "71f067a325424ee2a0f60858911d7eec":{
      "scriptId":"u34"},
    "5cbdbc70d6b147f188b8585fe028b90e":{
      "scriptId":"u35"},
    "e2423bb77f8c45fe987f1e72b76e0451":{
      "scriptId":"u36"},
    "c61b0070cacb4e81941172e25942e34c":{
      "scriptId":"u37"},
    "484551d0ecc947788e6c609122c91c22":{
      "scriptId":"u38"},
    "201538a7a31f4bc8a25b1fa863adf990":{
      "scriptId":"u39"},
    "c9771bf491ce4c3eab41a28ba8a456b3":{
      "scriptId":"u40"},
    "1f8fb9c787a84ab78bd4addf69948f9f":{
      "scriptId":"u41"},
    "a2c57acba7404ad5aef375c234872ad4":{
      "scriptId":"u42"},
    "2aab1c290e264e07b449dc37294ea127":{
      "scriptId":"u43"},
    "3ae520e4c232480083027cd08ad13dd9":{
      "scriptId":"u44"},
    "152b4dfe853345669a3773d162ff9ec7":{
      "scriptId":"u45"},
    "6d109fff0aa8425f9b0e7593abb731ef":{
      "scriptId":"u46"},
    "912e1117f2424fafb1dc9a74630c9091":{
      "scriptId":"u47"},
    "8599f74055d0468da11f665496f80f8e":{
      "scriptId":"u48"},
    "fd7bbcfe4a7e4edc8eec852708dff7f3":{
      "scriptId":"u49"},
    "16c1841a19924e13a6e710e1e9765580":{
      "scriptId":"u50"},
    "6e354c7546384cbab7327e46c88a69ab":{
      "scriptId":"u51"},
    "dfeda52efe754929b6fb817c0a0c341a":{
      "scriptId":"u52"},
    "397526209e0441ac9c9c713416c423f1":{
      "scriptId":"u53"},
    "eacfc219a3f644aeb2130b2c15736f4a":{
      "scriptId":"u54"},
    "d352f4b7de6d4eaeb52e289468a9640e":{
      "scriptId":"u55"},
    "ce61cf48e2d3402faec23b47479532b5":{
      "scriptId":"u56"},
    "5106243b20854c8489ed7a20eeab4d63":{
      "scriptId":"u57"},
    "59a51724ab414b6bbde19148ba47eb58":{
      "scriptId":"u58"},
    "f5b1c58aaf34490fa7609cb992eef8cf":{
      "scriptId":"u59"},
    "4fe17da1ee5b4847b0c256cdbd767a96":{
      "scriptId":"u60"},
    "a0e1c4ee165045329c365a1f343c8fe4":{
      "scriptId":"u61"},
    "c58a84fdfbaa4dafaa133dcc5123d803":{
      "scriptId":"u62"},
    "33a08ae5e3ce4a04b548561aa3ce6546":{
      "scriptId":"u63"},
    "1c565a3ce2bc4deebe9f730f4285413a":{
      "scriptId":"u64"},
    "b8da98bd5fa64e2b8ddb19c78df69ce1":{
      "scriptId":"u65"},
    "559da7c242e14e4b89728b0b31b17500":{
      "scriptId":"u66"},
    "d194c3685e23442b93f32f2bf887209d":{
      "scriptId":"u67"},
    "d34f2642d6984868b18dbc1b86a748b1":{
      "scriptId":"u68"},
    "4b9541a897514a20832c78cdc14f0fef":{
      "scriptId":"u69"},
    "78b18bd9192742a98dccb2fd1621f20e":{
      "scriptId":"u70"},
    "7df8a3c71fb145968f370aaeba480fa2":{
      "scriptId":"u71"},
    "4f6d3172597f4330b729b7815607b582":{
      "scriptId":"u72"},
    "2ee20dbaa0e244afa60a7618ea6ad520":{
      "scriptId":"u73"},
    "d2d42e468a734862ad81986a9b9d1e05":{
      "scriptId":"u74"},
    "7f1a642b37f3468fb43b1db6f62564f0":{
      "scriptId":"u75"},
    "e135169d148b493bb69104ad7c6c9d5d":{
      "scriptId":"u76"},
    "59a3decf774c435ea0ef352ac02c66ad":{
      "scriptId":"u77"},
    "695339a847304046927167ceb025e6a8":{
      "scriptId":"u78"},
    "99fca92e3af04ebc95785fdf93d50820":{
      "scriptId":"u79"},
    "7254bb20ae7d4b0ab92c023ae0cacf68":{
      "scriptId":"u80"},
    "7bfee84aba4d44d7ac104e51ff295d37":{
      "scriptId":"u81"},
    "f9336df9fc6643be93a54167ab5845d6":{
      "scriptId":"u82"},
    "17f2169a968b4b5fa0fbfb05edaeb617":{
      "scriptId":"u83"},
    "59d8dee67a9c429ea56999231fe6b623":{
      "scriptId":"u84"},
    "3643fae220ed47cea860f9188d795c3f":{
      "scriptId":"u85"},
    "2e048ed0e45545f3967351e772c50cc5":{
      "scriptId":"u86"},
    "3c2f83b7a93d4f64b7d4131fc33f7b1e":{
      "scriptId":"u87"},
    "d8aec3ea656e40c6b1490bd22c473490":{
      "scriptId":"u88"},
    "95f2c17a928244b58ac531b2e3d5cbeb":{
      "scriptId":"u89"},
    "28e8945c22914cf189cafd1cdf3432a2":{
      "scriptId":"u90"},
    "fbe7cb27631c41eb9589811b0ed26525":{
      "scriptId":"u91"},
    "59efdf698a4f4482982d6a0e8c013fde":{
      "scriptId":"u92"},
    "4336a1e247584cf68645fe6bd7067a27":{
      "scriptId":"u93"},
    "3a83d0dc3e72433dbef90c477e00f00a":{
      "scriptId":"u94"},
    "8ee2948f5ed9441cbfe1e6b766444b85":{
      "scriptId":"u95"},
    "8a6975cb8f954a09820bef9412754f97":{
      "scriptId":"u96"},
    "1e244d92eba74faaa805ffc64f119445":{
      "scriptId":"u97"},
    "ec542f1472674abca180a44e13dacbc3":{
      "scriptId":"u98"},
    "68221993ba9540a38354a185307ed9df":{
      "scriptId":"u99"},
    "6c7c75bdade242278859831c6087cd27":{
      "scriptId":"u100"},
    "8b97e429a6a14924a84734359b9d9282":{
      "scriptId":"u101"},
    "b60cbfbf6e924629a1b95219e6bcf07a":{
      "scriptId":"u102"}}});