/*var reportInfo = {
  "status": "S",
  "message": "",
  "data": [
    {
      "report_no": 7381,
      "aaid": "adhoc",
      "user_id": "alexandru.tomescu@hp.com",
      "is_fixed": "N",
      "datamart": "Detail",
      "name": "TEST",
      "type": null,
      "description": "... some longer description ... ",
      "show_filter_def": "1",
      "show_top": null,
      "keep_last": 3,
      "hidedups": 1,
      "server_format": "dhtmlie",
      "email_mode": "no",
      "email": "alexandru.tomescu@hp.com",
      "email_format": null,
      "sched_interval": "once",
      "sched_when": null,
      "sched_hour": 0,
      "sched_min": 0,
      "sched_timezone": null,
      "last_change": "2013-02-05T12:51:40.000Z",
      "options": "fullyexp",
      "is_shared": null,
      "profile": null,
      "reactivate_date": null,
      "reactivate_status": null,
      "disabled": null,
      "long_runner": null,
      "failures": null,
      "donot_create_empty": "0",
      "show_cancelled": null,
      "files": ""
    },
    {
      "report_no": 7382,
      "aaid": "adhoc",
      "user_id": "alexandru.tomescu@hp.com",
      "is_fixed": "N",
      "datamart": "Detail",
      "name": "Facebook",
      "type": null,
      "description": "... some longer description ... ",
      "show_filter_def": "1",
      "show_top": null,
      "keep_last": 3,
      "hidedups": 1,
      "server_format": "dhtmlie",
      "email_mode": "no",
      "email": "alexandru.tomescu@hp.com",
      "email_format": null,
      "sched_interval": "once",
      "sched_when": null,
      "sched_hour": 0,
      "sched_min": 0,
      "sched_timezone": null,
      "last_change": "2013-02-05T12:51:40.000Z",
      "options": "fullyexp",
      "is_shared": null,
      "profile": null,
      "reactivate_date": null,
      "reactivate_status": null,
      "disabled": null,
      "long_runner": null,
      "failures": null,
      "donot_create_empty": "0",
      "show_cancelled": null,
      "files": {
        "xls": "localhost:3000/ossui/v1/reports/getreport?aaid=adhoc&user=alexandru.tomescu@hp.com&report=7382&run=1&format=xls"
    }
    },
    {
      "report_no": 7383,
      "aaid": "adhoc",
      "user_id": "alexandru.tomescu@hp.com",
      "is_fixed": "N",
      "datamart": "Detail",
      "name": "MSFT",
      "type": null,
      "description": "... some longer description ... ",
      "show_filter_def": "1",
      "show_top": null,
      "keep_last": 3,
      "hidedups": 1,
      "server_format": "dhtmlie",
      "email_mode": "no",
      "email": "alexandru.tomescu@hp.com",
      "email_format": null,
      "sched_interval": "once",
      "sched_when": null,
      "sched_hour": 0,
      "sched_min": 0,
      "sched_timezone": null,
      "last_change": "2013-02-05T12:51:40.000Z",
      "options": "fullyexp",
      "is_shared": null,
      "profile": null,
      "reactivate_date": null,
      "reactivate_status": null,
      "disabled": null,
      "long_runner": null,
      "failures": null,
      "donot_create_empty": "0",
      "show_cancelled": null,
      "files": {
        "csv": "localhost:3000/ossui/v1/reports/getreport?aaid=adhoc&user=alexandru.tomescu@hp.com&report=7383&run=1&format=csv"
    }
    },
    {
      "report_no": 7384,
      "aaid": "adhoc",
      "user_id": "alexandru.tomescu@hp.com",
      "is_fixed": "N",
      "datamart": "Detail",
      "name": "Facebook",
      "type": null,
      "description": "... some longer description ... ",
      "show_filter_def": "1",
      "show_top": null,
      "keep_last": 3,
      "hidedups": 1,
      "server_format": "dhtmlie",
      "email_mode": "no",
      "email": "alexandru.tomescu@hp.com",
      "email_format": null,
      "sched_interval": "once",
      "sched_when": null,
      "sched_hour": 0,
      "sched_min": 0,
      "sched_timezone": null,
      "last_change": "2013-14-05T12:51:40.000Z",
      "options": "fullyexp",
      "is_shared": null,
      "profile": null,
      "reactivate_date": null,
      "reactivate_status": null,
      "disabled": null,
      "long_runner": null,
      "failures": null,
      "donot_create_empty": "0",
      "show_cancelled": null,
      "files": {
        "csv": "localhost:3000/ossui/v1/reports/getreport?aaid=adhoc&user=alexandru.tomescu@hp.com&report=7384&run=1&format=csv",
        "xls": "localhost:3000/ossui/v1/reports/getreport?aaid=adhoc&user=alexandru.tomescu@hp.com&report=7384&run=1&format=xls"
    }
    },
    {
      "report_no": 7385,
      "aaid": "adhoc",
      "user_id": "alexandru.tomescu@hp.com",
      "is_fixed": "N",
      "datamart": "Detail",
      "name": "Apple",
      "type": null,
      "description": "... some longer description ... ",
      "show_filter_def": "1",
      "show_top": null,
      "keep_last": 3,
      "hidedups": 1,
      "server_format": "dhtmlie",
      "email_mode": "no",
      "email": "alexandru.tomescu@hp.com",
      "email_format": null,
      "sched_interval": "once",
      "sched_when": null,
      "sched_hour": 0,
      "sched_min": 0,
      "sched_timezone": null,
      "last_change": "2013-14-05T12:51:40.000Z",
      "options": "fullyexp",
      "is_shared": null,
      "profile": null,
      "reactivate_date": null,
      "reactivate_status": null,
      "disabled": null,
      "long_runner": null,
      "failures": null,
      "donot_create_empty": "0",
      "show_cancelled": null,
      "files": {
        "csv": "localhost:3000/ossui/v1/reports/getreport?aaid=adhoc&user=alexandru.tomescu@hp.com&report=7385&run=1&format=csv",
        "xls": "localhost:3000/ossui/v1/reports/getreport?aaid=adhoc&user=alexandru.tomescu@hp.com&report=7385&run=1&format=xls"
      }
    }
  ]
};*/




var reportInfo = {
    "status": "S",
    "message": "",
    "data": [{
            "report_no": 25661,
            "aaid": "adhoc",
            "user_id": "hymavathi.vajrala@hp.com",
            "is_fixed": "N",
            "datamart": "Material",
            "name": "Facebook",
            "type": null,
            "description": "... some longer description ... ",
            "show_filter_def": "1",
            "show_top": null,
            "keep_last": 3,
            "hidedups": 1,
            "server_format": "csv xls",
            "email_mode": "no",
            "email": "hymavathi.vajrala@hp.com",
            "email_format": null,
            "sched_interval": "once",
            "sched_when": null,
            "sched_hour": 0,
            "sched_min": 0,
            "sched_timezone": null,
            "last_change": "2013-06-11T07:01:54.000Z",
            "options": "fullyexp",
            "is_shared": null,
            "profile": null,
            "reactivate_date": null,
            "reactivate_status": null,
            "disabled": null,
            "long_runner": null,
            "failures": "0",
            "donot_create_empty": "0",
            "show_cancelled": "0",
            "files": {
                "csv": [{
                        "run_no": 1,
                        "comment_text": null,
                        "started_at": "2013-06-11T07:01:55.000Z",
                        "ended_at": "2013-06-11T07:02:22.000Z",
                        "report_file": "localhost:3000/ossui/v1/reports/getreport?aaid=adhoc&user=hymavathi.vajrala@hp.com&report=25661&run=1&format=csv"
                    }
                ],
                "xls": [{
                        "run_no": 1,
                        "comment_text": null,
                        "started_at": "2013-06-11T07:01:55.000Z",
                        "ended_at": "2013-06-11T07:02:22.000Z",
                        "report_file": "localhost:3000/ossui/v1/reports/getreport?aaid=adhoc&user=hymavathi.vajrala@hp.com&report=25661&run=1&format=xls"
                    }
                ]
            }
        }, {
            "report_no": 25663,
            "aaid": "adhoc",
            "user_id": "hymavathi.vajrala@hp.com",
            "is_fixed": "N",
            "datamart": "Material",
            "name": "Test",
            "type": null,
            "description": "... some longer description ... ",
            "show_filter_def": "1",
            "show_top": null,
            "keep_last": 3,
            "hidedups": 1,
            "server_format": "csv",
            "email_mode": "no",
            "email": "hymavathi.vajrala@hp.com",
            "email_format": null,
            "sched_interval": "once",
            "sched_when": null,
            "sched_hour": 0,
            "sched_min": 0,
            "sched_timezone": null,
            "last_change": "2013-06-11T07:26:07.000Z",
            "options": "fullyexp",
            "is_shared": null,
            "profile": null,
            "reactivate_date": null,
            "reactivate_status": null,
            "disabled": null,
            "long_runner": "1",
            "failures": null,
            "donot_create_empty": "0",
            "show_cancelled": "0",
            "files": {

            }
        }, {
            "report_no": 25662,
            "aaid": "adhoc",
            "user_id": "hymavathi.vajrala@hp.com",
            "is_fixed": "N",
            "datamart": "Material",
            "name": "MSFT",
            "type": null,
            "description": "... some longer description ... ",
            "show_filter_def": "1",
            "show_top": null,
            "keep_last": 3,
            "hidedups": 1,
            "server_format": "csv xls",
            "email_mode": "no",
            "email": "hymavathi.vajrala@hp.com",
            "email_format": null,
            "sched_interval": "once",
            "sched_when": null,
            "sched_hour": 0,
            "sched_min": 0,
            "sched_timezone": null,
            "last_change": "2013-06-11T07:19:34.000Z",
            "options": "fullyexp",
            "is_shared": null,
            "profile": null,
            "reactivate_date": null,
            "reactivate_status": null,
            "disabled": null,
            "long_runner": null,
            "failures": "0",
            "donot_create_empty": "0",
            "show_cancelled": "0",
            "files": {
                "csv": [{
                        "run_no": 1,
                        "comment_text": null,
                        "started_at": "2013-06-11T07:19:41.000Z",
                        "ended_at": "2013-06-11T07:20:03.000Z",
                        "report_file": "localhost:3000/ossui/v1/reports/getreport?aaid=adhoc&user=hymavathi.vajrala@hp.com&report=25662&run=1&format=csv"
                    }, {
                        "run_no": 2,
                        "comment_text": null,
                        "started_at": "2013-06-11T07:21:47.000Z",
                        "ended_at": "2013-06-11T07:21:59.000Z",
                        "report_file": "localhost:3000/ossui/v1/reports/getreport?aaid=adhoc&user=hymavathi.vajrala@hp.com&report=25662&run=2&format=csv"
                    }
                ],
                "xls": [{
                        "run_no": 1,
                        "comment_text": null,
                        "started_at": "2013-06-11T07:19:41.000Z",
                        "ended_at": "2013-06-11T07:20:03.000Z",
                        "report_file": "localhost:3000/ossui/v1/reports/getreport?aaid=adhoc&user=hymavathi.vajrala@hp.com&report=25662&run=1&format=xls"
                    }, {
                        "run_no": 2,
                        "comment_text": null,
                        "started_at": "2013-06-11T07:21:47.000Z",
                        "ended_at": "2013-06-11T07:21:59.000Z",
                        "report_file": "localhost:3000/ossui/v1/reports/getreport?aaid=adhoc&user=hymavathi.vajrala@hp.com&report=25662&run=2&format=xls"
                    }
                ]
            }
        }
    ]
}
